CREATE TABLE `catalog_products` (
	`id` text PRIMARY KEY NOT NULL,
	`category_id` text NOT NULL,
	`factory_id` text,
	`manufacturer` text NOT NULL,
	`brand` text NOT NULL,
	`product_code` text NOT NULL,
	`product_name` text NOT NULL,
	`series` text DEFAULT '' NOT NULL,
	`model` text NOT NULL,
	`description` text DEFAULT '' NOT NULL,
	`country` text DEFAULT '' NOT NULL,
	`lifecycle_status` text DEFAULT 'active' NOT NULL,
	`applicable_systems_json` text DEFAULT '[]' NOT NULL,
	`media_json` text DEFAULT '[]' NOT NULL,
	`min_pressure_mpa` real,
	`max_pressure_mpa` real,
	`min_temperature_c` real,
	`max_temperature_c` real,
	`nominal_size` text,
	`connection_standard` text,
	`wetted_materials_json` text DEFAULT '[]' NOT NULL,
	`surface_finish` text,
	`cleanliness_grade` text,
	`max_flow` real,
	`flow_unit` text,
	`supply_voltage` text,
	`signal_protocol` text,
	`ingress_protection` text,
	`hazardous_area_rating` text,
	`certifications_json` text DEFAULT '[]' NOT NULL,
	`standards_json` text DEFAULT '[]' NOT NULL,
	`specifications_json` text DEFAULT '{}' NOT NULL,
	`source_document` text,
	`source_url` text,
	`source_page` text,
	`revision` text DEFAULT 'A' NOT NULL,
	`status` text DEFAULT 'draft' NOT NULL,
	`created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	`updated_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	FOREIGN KEY (`category_id`) REFERENCES `product_categories`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`factory_id`) REFERENCES `equipment_factories`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE UNIQUE INDEX `catalog_products_brand_code_uq` ON `catalog_products` (`brand`,`product_code`);--> statement-breakpoint
CREATE INDEX `catalog_products_category_idx` ON `catalog_products` (`category_id`);--> statement-breakpoint
CREATE INDEX `catalog_products_model_idx` ON `catalog_products` (`model`);--> statement-breakpoint
CREATE INDEX `catalog_products_status_idx` ON `catalog_products` (`status`);--> statement-breakpoint
CREATE TABLE `product_applications` (
	`id` text PRIMARY KEY NOT NULL,
	`product_id` text NOT NULL,
	`system_code` text NOT NULL,
	`service` text NOT NULL,
	`medium` text DEFAULT '' NOT NULL,
	`suitability` text DEFAULT 'approved' NOT NULL,
	`limitations` text DEFAULT '' NOT NULL,
	`created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	`updated_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	FOREIGN KEY (`product_id`) REFERENCES `catalog_products`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE UNIQUE INDEX `product_applications_product_system_service_uq` ON `product_applications` (`product_id`,`system_code`,`service`);--> statement-breakpoint
CREATE INDEX `product_applications_system_idx` ON `product_applications` (`system_code`,`suitability`);--> statement-breakpoint
CREATE TABLE `product_categories` (
	`id` text PRIMARY KEY NOT NULL,
	`code` text NOT NULL,
	`name` text NOT NULL,
	`parent_code` text,
	`discipline` text NOT NULL,
	`applicable_systems_json` text DEFAULT '[]' NOT NULL,
	`icon` text DEFAULT '◇' NOT NULL,
	`description` text DEFAULT '' NOT NULL,
	`status` text DEFAULT 'active' NOT NULL,
	`created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	`updated_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX `product_categories_code_uq` ON `product_categories` (`code`);--> statement-breakpoint
CREATE INDEX `product_categories_discipline_idx` ON `product_categories` (`discipline`);--> statement-breakpoint
CREATE TABLE `product_parameter_definitions` (
	`id` text PRIMARY KEY NOT NULL,
	`category_id` text NOT NULL,
	`key` text NOT NULL,
	`label` text NOT NULL,
	`group_name` text DEFAULT '详细规格' NOT NULL,
	`data_type` text DEFAULT 'text' NOT NULL,
	`unit` text,
	`required` integer DEFAULT false NOT NULL,
	`comparable` integer DEFAULT true NOT NULL,
	`options_json` text DEFAULT '[]' NOT NULL,
	`validation_json` text DEFAULT '{}' NOT NULL,
	`sort_order` integer DEFAULT 0 NOT NULL,
	`help_text` text DEFAULT '' NOT NULL,
	`status` text DEFAULT 'active' NOT NULL,
	`created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	`updated_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	FOREIGN KEY (`category_id`) REFERENCES `product_categories`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE UNIQUE INDEX `product_parameter_definitions_category_key_uq` ON `product_parameter_definitions` (`category_id`,`key`);--> statement-breakpoint
CREATE INDEX `product_parameter_definitions_category_idx` ON `product_parameter_definitions` (`category_id`,`sort_order`);--> statement-breakpoint
CREATE TABLE `product_variants` (
	`id` text PRIMARY KEY NOT NULL,
	`product_id` text NOT NULL,
	`sku` text NOT NULL,
	`option_code` text DEFAULT '' NOT NULL,
	`name` text NOT NULL,
	`specifications_json` text DEFAULT '{}' NOT NULL,
	`dimensions_json` text DEFAULT '{}' NOT NULL,
	`weight_kg` real,
	`lead_time_weeks` integer,
	`unit_price_cny` real,
	`status` text DEFAULT 'active' NOT NULL,
	`created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	`updated_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	FOREIGN KEY (`product_id`) REFERENCES `catalog_products`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE UNIQUE INDEX `product_variants_product_sku_uq` ON `product_variants` (`product_id`,`sku`);--> statement-breakpoint
CREATE INDEX `product_variants_product_idx` ON `product_variants` (`product_id`);
--> statement-breakpoint
INSERT OR IGNORE INTO product_categories (id,code,name,discipline,applicable_systems_json,icon,description,status) VALUES ('cat-regulator','REGULATOR','调压阀 / 背压阀','Process / Mechanical','["SGAS","BSGS","CDS","HUP","CDA","PCW","CHW","UPW","WWT","EXH","FIRE"]','◉','高纯、特气、化学品及公用工程调压与背压控制。','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-regulator-regulationType','cat-regulator','regulationType','调压形式','性能','select',NULL,1,1,'["single_stage","dual_stage","back_pressure","dome_loaded"]','{}',10,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-regulator-inletPressureRating','cat-regulator','inletPressureRating','入口额定压力','压力与流量','number','MPa',1,1,'[]','{"min":0}',20,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-regulator-outletPressureRange','cat-regulator','outletPressureRange','出口压力范围','压力与流量','text','MPa',1,1,'[]','{}',30,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-regulator-cv','cat-regulator','cv','流量系数 Cv','压力与流量','number','Cv',1,1,'[]','{"min":0}',40,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-regulator-seatMaterial','cat-regulator','seatMaterial','阀座材质','材料与洁净','text',NULL,1,1,'[]','{}',50,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-regulator-internalLeakRate','cat-regulator','internalLeakRate','内漏率','泄漏与测试','text',NULL,0,1,'[]','{}',60,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-regulator-externalLeakRate','cat-regulator','externalLeakRate','外漏率','泄漏与测试','text',NULL,0,1,'[]','{}',70,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-regulator-proofPressure','cat-regulator','proofPressure','耐压试验压力','泄漏与测试','number','MPa',0,1,'[]','{}',80,'','active');
INSERT OR IGNORE INTO product_categories (id,code,name,discipline,applicable_systems_json,icon,description,status) VALUES ('cat-diaphragm-valve','DIAPHRAGM_VALVE','隔膜阀','Process / Mechanical','["SGAS","BSGS","CDS","HUP","CDA","PCW","CHW","UPW","WWT","EXH","FIRE"]','◒','手动或气动高纯隔膜阀、波纹管阀与切断阀。','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-diaphragm_valve-actuation','cat-diaphragm-valve','actuation','驱动方式','执行机构','select',NULL,1,1,'["manual","normally_closed","normally_open","double_acting"]','{}',10,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-diaphragm_valve-cv','cat-diaphragm-valve','cv','流量系数 Cv','性能','number','Cv',1,1,'[]','{}',20,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-diaphragm_valve-seatMaterial','cat-diaphragm-valve','seatMaterial','阀座材质','材料与洁净','text',NULL,1,1,'[]','{}',30,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-diaphragm_valve-diaphragmMaterial','cat-diaphragm-valve','diaphragmMaterial','隔膜材质','材料与洁净','text',NULL,1,1,'[]','{}',40,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-diaphragm_valve-cycleLife','cat-diaphragm-valve','cycleLife','设计循环寿命','寿命','number','cycles',0,1,'[]','{}',50,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-diaphragm_valve-actuationPressure','cat-diaphragm-valve','actuationPressure','执行气压力','执行机构','text','MPa',0,1,'[]','{}',60,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-diaphragm_valve-leakRate','cat-diaphragm-valve','leakRate','氦检漏率','泄漏与测试','text',NULL,0,1,'[]','{}',70,'','active');
INSERT OR IGNORE INTO product_categories (id,code,name,discipline,applicable_systems_json,icon,description,status) VALUES ('cat-check-bellows','CHECK_BELLOWS_VALVE','止回阀 / 波纹管阀','Process / Mechanical','["SGAS","BSGS","CDS","HUP","CDA","PCW","CHW","UPW","WWT","EXH","FIRE"]','⇥','止回、单向控制、波纹管密封与安全隔离阀。','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-check_bellows_valve-valveType','cat-check-bellows','valveType','阀门形式','结构','select',NULL,1,1,'["check","bellows","needle","relief"]','{}',10,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-check_bellows_valve-crackingPressure','cat-check-bellows','crackingPressure','开启压力','性能','text','bar',1,1,'[]','{}',20,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-check_bellows_valve-resealPressure','cat-check-bellows','resealPressure','回座压力','性能','text','bar',0,1,'[]','{}',30,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-check_bellows_valve-cv','cat-check-bellows','cv','流量系数 Cv','性能','number','Cv',0,1,'[]','{}',40,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-check_bellows_valve-sealMaterial','cat-check-bellows','sealMaterial','密封材质','材料','text',NULL,1,1,'[]','{}',50,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-check_bellows_valve-flowDirection','cat-check-bellows','flowDirection','流向','结构','select',NULL,0,1,'["unidirectional","bidirectional"]','{}',60,'','active');
INSERT OR IGNORE INTO product_categories (id,code,name,discipline,applicable_systems_json,icon,description,status) VALUES ('cat-fitting-tubing','FITTING_TUBING','管件 / 管材 / 软管','Piping','["SGAS","BSGS","CDS","HUP","CDA","PCW","CHW","UPW","WWT","EXH","FIRE"]','⌁','VCR/VCO、卡套、焊接、法兰、PFA/PVDF 管件与软管。','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-fitting_tubing-componentType','cat-fitting-tubing','componentType','部件类型','分类','select',NULL,1,1,'["tube","fitting","gasket","hose","flange","adapter"]','{}',10,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-fitting_tubing-scheduleOrWall','cat-fitting-tubing','scheduleOrWall','壁厚 / Schedule','尺寸','text',NULL,0,1,'[]','{}',20,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-fitting_tubing-end1','cat-fitting-tubing','end1','端口 1','接口','text',NULL,1,1,'[]','{}',30,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-fitting_tubing-end2','cat-fitting-tubing','end2','端口 2','接口','text',NULL,0,1,'[]','{}',40,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-fitting_tubing-gasketMaterial','cat-fitting-tubing','gasketMaterial','垫片材质','材料','text',NULL,0,1,'[]','{}',50,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-fitting_tubing-bendRadius','cat-fitting-tubing','bendRadius','最小弯曲半径','尺寸','number','mm',0,1,'[]','{}',60,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-fitting_tubing-cleaningSpecification','cat-fitting-tubing','cleaningSpecification','清洗包装规范','洁净','text',NULL,0,1,'[]','{}',70,'','active');
INSERT OR IGNORE INTO product_categories (id,code,name,discipline,applicable_systems_json,icon,description,status) VALUES ('cat-purifier-filter','GAS_PURIFIER_FILTER','气体净化器 / 过滤器','Process','["SGAS","BSGS","HUP","CDA"]','◈','点位及大宗气体净化、颗粒过滤与吸附单元。','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-gas_purifier_filter-gasFamily','cat-purifier-filter','gasFamily','适用气体族','应用','text',NULL,1,1,'[]','{}',10,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-gas_purifier_filter-removalContaminants','cat-purifier-filter','removalContaminants','去除污染物','净化性能','text',NULL,1,1,'[]','{}',20,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-gas_purifier_filter-outletPurity','cat-purifier-filter','outletPurity','出口纯度 / 保证值','净化性能','text','ppb/ppt',0,1,'[]','{}',30,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-gas_purifier_filter-filterRating','cat-purifier-filter','filterRating','过滤精度','过滤性能','text','nm/µm',1,1,'[]','{}',40,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-gas_purifier_filter-ratedFlow','cat-purifier-filter','ratedFlow','额定流量','流量','number','slpm',0,1,'[]','{}',50,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-gas_purifier_filter-pressureDrop','cat-purifier-filter','pressureDrop','额定流量压降','流量','text','kPa',0,1,'[]','{}',60,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-gas_purifier_filter-mediaMaterial','cat-purifier-filter','mediaMaterial','净化 / 滤芯介质','材料','text',NULL,0,1,'[]','{}',70,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-gas_purifier_filter-serviceLife','cat-purifier-filter','serviceLife','设计寿命 / 容量','寿命','text',NULL,0,1,'[]','{}',80,'','active');
INSERT OR IGNORE INTO product_categories (id,code,name,discipline,applicable_systems_json,icon,description,status) VALUES ('cat-pressure-instrument','PRESSURE_INSTRUMENT','压力表 / 压力变送器','Instrumentation','["SGAS","BSGS","CDS","HUP","CDA","PCW","CHW","UPW","WWT","EXH","FIRE"]','◎','机械压力表、压力变送器、差压变送器与电子压力开关。','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-pressure_instrument-instrumentType','cat-pressure-instrument','instrumentType','仪表类型','分类','select',NULL,1,1,'["gauge","transmitter","switch","differential"]','{}',10,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-pressure_instrument-measuringRange','cat-pressure-instrument','measuringRange','量程','测量','text',NULL,1,1,'[]','{}',20,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-pressure_instrument-accuracy','cat-pressure-instrument','accuracy','精度','测量','text','%FS',1,1,'[]','{}',30,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-pressure_instrument-outputSignal','cat-pressure-instrument','outputSignal','输出信号','电气与信号','text',NULL,0,1,'[]','{}',40,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-pressure_instrument-processConnection','cat-pressure-instrument','processConnection','过程连接','接口','text',NULL,1,1,'[]','{}',50,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-pressure_instrument-overpressureLimit','cat-pressure-instrument','overpressureLimit','过压能力','测量','text',NULL,0,1,'[]','{}',60,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-pressure_instrument-displayDiameter','cat-pressure-instrument','displayDiameter','表盘直径','机械','number','mm',0,1,'[]','{}',70,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-pressure_instrument-heliumLeakRate','cat-pressure-instrument','heliumLeakRate','氦检漏率','洁净','text',NULL,0,1,'[]','{}',80,'','active');
INSERT OR IGNORE INTO product_categories (id,code,name,discipline,applicable_systems_json,icon,description,status) VALUES ('cat-flow-temperature','FLOW_TEMPERATURE_INSTRUMENT','流量 / 温度 / 分析仪表','Instrumentation','["SGAS","BSGS","CDS","HUP","CDA","PCW","CHW","UPW","WWT","EXH","FIRE"]','∿','流量计、温度元件、露点、纯度、pH/电导率及气体分析仪。','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-flow_temperature_instrument-measuredVariable','cat-flow-temperature','measuredVariable','测量变量','测量','text',NULL,1,1,'[]','{}',10,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-flow_temperature_instrument-measuringRange','cat-flow-temperature','measuringRange','量程','测量','text',NULL,1,1,'[]','{}',20,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-flow_temperature_instrument-accuracy','cat-flow-temperature','accuracy','精度','测量','text',NULL,1,1,'[]','{}',30,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-flow_temperature_instrument-outputSignal','cat-flow-temperature','outputSignal','输出 / 通讯','电气与信号','text',NULL,0,1,'[]','{}',40,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-flow_temperature_instrument-responseTime','cat-flow-temperature','responseTime','响应时间','性能','text',NULL,0,1,'[]','{}',50,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-flow_temperature_instrument-calibration','cat-flow-temperature','calibration','校准 / 溯源','质量','text',NULL,0,1,'[]','{}',60,'','active');
INSERT OR IGNORE INTO product_categories (id,code,name,discipline,applicable_systems_json,icon,description,status) VALUES ('cat-pump','PUMP','泵','Mechanical','["CDS","PCW","CHW","UPW","WWT","EXH","FIRE"]','◉','离心泵、磁力泵、计量泵、真空泵和消防泵。','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-pump-pumpType','cat-pump','pumpType','泵型','结构','text',NULL,1,1,'[]','{}',10,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-pump-ratedFlow','cat-pump','ratedFlow','额定流量','性能','number','m³/h',1,1,'[]','{}',20,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-pump-ratedHead','cat-pump','ratedHead','额定扬程','性能','number','m',1,1,'[]','{}',30,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-pump-npshr','cat-pump','npshr','NPSHr','性能','number','m',0,1,'[]','{}',40,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-pump-efficiency','cat-pump','efficiency','效率','性能','number','%',0,1,'[]','{}',50,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-pump-motorPower','cat-pump','motorPower','电机功率','电机','number','kW',1,1,'[]','{}',60,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-pump-motorEfficiencyClass','cat-pump','motorEfficiencyClass','电机能效等级','电机','text',NULL,0,1,'[]','{}',70,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-pump-sealType','cat-pump','sealType','轴封形式','材料与结构','text',NULL,0,1,'[]','{}',80,'','active');
INSERT OR IGNORE INTO product_categories (id,code,name,discipline,applicable_systems_json,icon,description,status) VALUES ('cat-compressor','COMPRESSOR_BLOWER','压缩机 / 风机 / 鼓风机','Mechanical','["CDA","EXH","CR","WWT"]','≈','空压机、排风机、洁净风机、废水鼓风机与真空机组。','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-compressor_blower-machineType','cat-compressor','machineType','机型','结构','text',NULL,1,1,'[]','{}',10,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-compressor_blower-ratedFlow','cat-compressor','ratedFlow','额定流量','性能','number','m³/h',1,1,'[]','{}',20,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-compressor_blower-pressureOrStatic','cat-compressor','pressureOrStatic','排压 / 静压','性能','text','kPa',1,1,'[]','{}',30,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-compressor_blower-motorPower','cat-compressor','motorPower','电机功率','电机','number','kW',1,1,'[]','{}',40,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-compressor_blower-noise','cat-compressor','noise','噪声','环境','number','dB(A)',0,1,'[]','{}',50,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-compressor_blower-vibration','cat-compressor','vibration','振动等级','机械','text',NULL,0,1,'[]','{}',60,'','active');
INSERT OR IGNORE INTO product_categories (id,code,name,discipline,applicable_systems_json,icon,description,status) VALUES ('cat-water-treatment','WATER_TREATMENT','纯废水处理单元','Water','["UPW","WWT"]','≋','RO、EDI、UF、树脂塔、膜组件、加药和废水处理设备。','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-water_treatment-processType','cat-water-treatment','processType','处理工艺','工艺','text',NULL,1,1,'[]','{}',10,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-water_treatment-capacity','cat-water-treatment','capacity','处理能力','工艺','number','m³/h',1,1,'[]','{}',20,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-water_treatment-recovery','cat-water-treatment','recovery','回收率','性能','number','%',0,1,'[]','{}',30,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-water_treatment-productQuality','cat-water-treatment','productQuality','产水 / 出水指标','性能','text',NULL,1,1,'[]','{}',40,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-water_treatment-membraneOrMedia','cat-water-treatment','membraneOrMedia','膜 / 树脂 / 填料','材料','text',NULL,0,1,'[]','{}',50,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-water_treatment-cipRequirement','cat-water-treatment','cipRequirement','CIP 要求','运维','text',NULL,0,1,'[]','{}',60,'','active');
INSERT OR IGNORE INTO product_categories (id,code,name,discipline,applicable_systems_json,icon,description,status) VALUES ('cat-cleanroom-hvac','CLEANROOM_HVAC','洁净空调 / 过滤器','HVAC / Cleanroom','["CR"]','▦','MAU、AHU、FFU、HEPA/ULPA、风阀和洁净室末端。','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-cleanroom_hvac-equipmentType','cat-cleanroom-hvac','equipmentType','设备类型','分类','text',NULL,1,1,'[]','{}',10,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-cleanroom_hvac-airflow','cat-cleanroom-hvac','airflow','额定风量','空气性能','number','m³/h',1,1,'[]','{}',20,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-cleanroom_hvac-externalStaticPressure','cat-cleanroom-hvac','externalStaticPressure','机外静压','空气性能','number','Pa',0,1,'[]','{}',30,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-cleanroom_hvac-filterClass','cat-cleanroom-hvac','filterClass','过滤等级','过滤','text',NULL,1,1,'[]','{}',40,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-cleanroom_hvac-initialPressureDrop','cat-cleanroom-hvac','initialPressureDrop','初阻力','过滤','number','Pa',0,1,'[]','{}',50,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-cleanroom_hvac-dimensions','cat-cleanroom-hvac','dimensions','外形 / 过滤器尺寸','尺寸','text','mm',0,1,'[]','{}',60,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-cleanroom_hvac-fanPower','cat-cleanroom-hvac','fanPower','风机功率','电气','number','kW',0,1,'[]','{}',70,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-cleanroom_hvac-leakageClass','cat-cleanroom-hvac','leakageClass','泄漏等级','性能','text',NULL,0,1,'[]','{}',80,'','active');
INSERT OR IGNORE INTO product_categories (id,code,name,discipline,applicable_systems_json,icon,description,status) VALUES ('cat-exhaust-abatement','EXHAUST_ABATEMENT','工艺排风 / 废气处理','Exhaust / Environmental','["EXH","HUP"]','↟','酸碱/溶剂排风、Local Scrubber、洗涤塔、RTO 与监测单元。','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-exhaust_abatement-abatementType','cat-exhaust-abatement','abatementType','处理方式','工艺','text',NULL,1,1,'[]','{}',10,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-exhaust_abatement-airflow','cat-exhaust-abatement','airflow','处理风量','性能','number','m³/h',1,1,'[]','{}',20,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-exhaust_abatement-removalEfficiency','cat-exhaust-abatement','removalEfficiency','去除效率','性能','text','%',1,1,'[]','{}',30,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-exhaust_abatement-pressureDrop','cat-exhaust-abatement','pressureDrop','系统压降','性能','number','Pa',0,1,'[]','{}',40,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-exhaust_abatement-constructionMaterial','cat-exhaust-abatement','constructionMaterial','壳体 / 风管材质','材料','text',NULL,1,1,'[]','{}',50,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-exhaust_abatement-chemicalConsumption','cat-exhaust-abatement','chemicalConsumption','药剂消耗','运行','text',NULL,0,1,'[]','{}',60,'','active');
INSERT OR IGNORE INTO product_categories (id,code,name,discipline,applicable_systems_json,icon,description,status) VALUES ('cat-fire-detector','FIRE_GAS_DETECTOR','火焰 / 气体 / 消防探测','Fire & Life Safety','["FIRE","SGAS","CDS","HUP"]','△','火焰、可燃/有毒气体、烟感、VESDA 及消防报警设备。','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-fire_gas_detector-detectorType','cat-fire-detector','detectorType','探测原理','探测','text',NULL,1,1,'[]','{}',10,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-fire_gas_detector-detectionRange','cat-fire-detector','detectionRange','探测距离 / 量程','探测','text',NULL,1,1,'[]','{}',20,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-fire_gas_detector-fieldOfView','cat-fire-detector','fieldOfView','视场角','探测','text','degree',0,1,'[]','{}',30,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-fire_gas_detector-responseTime','cat-fire-detector','responseTime','响应时间','探测','text','s',0,1,'[]','{}',40,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-fire_gas_detector-analogOutput','cat-fire-detector','analogOutput','模拟量输出','接口','text',NULL,0,1,'[]','{}',50,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-fire_gas_detector-relayOutputs','cat-fire-detector','relayOutputs','继电器输出','接口','text',NULL,0,1,'[]','{}',60,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-fire_gas_detector-selfTest','cat-fire-detector','selfTest','自检功能','诊断','boolean',NULL,0,1,'[]','{}',70,'','active');
INSERT OR IGNORE INTO product_categories (id,code,name,discipline,applicable_systems_json,icon,description,status) VALUES ('cat-hmi-control','HMI_PLC_IO','HMI / PLC / I/O / 控制器','Controls','["CTRL","SGAS","CDS","HUP","CDA","PCW","CHW","CR","UPW","WWT","EXH","FIRE"]','▣','人机界面、PLC、远程 I/O、控制器与 BMS/SCADA 接口设备。','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-hmi_plc_io-deviceType','cat-hmi-control','deviceType','设备类型','分类','text',NULL,1,1,'[]','{}',10,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-hmi_plc_io-displaySize','cat-hmi-control','displaySize','屏幕尺寸','显示','number','inch',0,1,'[]','{}',20,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-hmi_plc_io-resolution','cat-hmi-control','resolution','分辨率','显示','text','pixel',0,1,'[]','{}',30,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-hmi_plc_io-displayColors','cat-hmi-control','displayColors','显示色数','显示','text',NULL,0,1,'[]','{}',40,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-hmi_plc_io-memory','cat-hmi-control','memory','用户内存','性能','text',NULL,0,1,'[]','{}',50,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-hmi_plc_io-interfaces','cat-hmi-control','interfaces','物理接口','通讯','text',NULL,1,1,'[]','{}',60,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-hmi_plc_io-engineeringSoftware','cat-hmi-control','engineeringSoftware','组态软件 / 版本','软件','text',NULL,0,1,'[]','{}',70,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-hmi_plc_io-mounting','cat-hmi-control','mounting','安装方式','机械','text',NULL,0,1,'[]','{}',80,'','active');
INSERT OR IGNORE INTO product_categories (id,code,name,discipline,applicable_systems_json,icon,description,status) VALUES ('cat-electrical','ELECTRICAL_DISTRIBUTION','变配电 / UPS / 配电设备','Electrical','["CTRL","CR","UPW","WWT","EXH","FIRE"]','ϟ','变压器、开关柜、UPS、PDU、配电箱、电缆和桥架。','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-electrical_distribution-equipmentType','cat-electrical','equipmentType','设备类型','分类','text',NULL,1,1,'[]','{}',10,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-electrical_distribution-ratedVoltage','cat-electrical','ratedVoltage','额定电压','电气','text','V/kV',1,1,'[]','{}',20,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-electrical_distribution-ratedCurrent','cat-electrical','ratedCurrent','额定电流','电气','number','A',0,1,'[]','{}',30,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-electrical_distribution-ratedPower','cat-electrical','ratedPower','额定容量','电气','text','kVA/MVA',0,1,'[]','{}',40,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-electrical_distribution-shortCircuitRating','cat-electrical','shortCircuitRating','短路耐受 / 分断能力','电气','text','kA',0,1,'[]','{}',50,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-electrical_distribution-formOfSeparation','cat-electrical','formOfSeparation','柜内分隔形式','结构','text',NULL,0,1,'[]','{}',60,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-electrical_distribution-energyEfficiency','cat-electrical','energyEfficiency','能效 / 效率','性能','text',NULL,0,1,'[]','{}',70,'','active');
INSERT OR IGNORE INTO product_categories (id,code,name,discipline,applicable_systems_json,icon,description,status) VALUES ('cat-network-fiber','NETWORK_FIBER','工业网络 / 网线 / 光纤','Controls / ELV','["CTRL"]','⌘','工业以太网交换机、铜缆、光缆、模块、跳线与协议网关。','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-network_fiber-productType','cat-network-fiber','productType','产品类型','分类','text',NULL,1,1,'[]','{}',10,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-network_fiber-networkCategory','cat-network-fiber','networkCategory','网络类别 / 速率','网络','text',NULL,1,1,'[]','{}',20,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-network_fiber-fiberType','cat-network-fiber','fiberType','光纤类型','光学','text',NULL,0,1,'[]','{}',30,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-network_fiber-coreCount','cat-network-fiber','coreCount','芯数 / 对数','结构','number',NULL,0,1,'[]','{}',40,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-network_fiber-connectorType','cat-network-fiber','connectorType','连接器','接口','text',NULL,0,1,'[]','{}',50,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-network_fiber-jacketMaterial','cat-network-fiber','jacketMaterial','护套材质 / 阻燃等级','材料','text',NULL,0,1,'[]','{}',60,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-network_fiber-transmissionDistance','cat-network-fiber','transmissionDistance','传输距离','网络','text','m/km',0,1,'[]','{}',70,'','active');
INSERT OR IGNORE INTO product_categories (id,code,name,discipline,applicable_systems_json,icon,description,status) VALUES ('cat-terminal','TERMINAL_ACCESSORY','端子 / 隔离器 / 电气附件','Electrical / Controls','["CTRL"]','⊞','接线端子、隔离器、安全栅、继电器、电源和浪涌保护。','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-terminal_accessory-connectionTechnology','cat-terminal','connectionTechnology','接线技术','结构','text',NULL,1,1,'[]','{}',10,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-terminal_accessory-ratedVoltage','cat-terminal','ratedVoltage','额定电压','电气','number','V',1,1,'[]','{}',20,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-terminal_accessory-ratedCurrent','cat-terminal','ratedCurrent','额定电流','电气','number','A',1,1,'[]','{}',30,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-terminal_accessory-wireRange','cat-terminal','wireRange','导线范围','接线','text','mm²/AWG',1,1,'[]','{}',40,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-terminal_accessory-impulseVoltage','cat-terminal','impulseVoltage','额定冲击耐压','电气','number','kV',0,1,'[]','{}',50,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-terminal_accessory-mountingRail','cat-terminal','mountingRail','安装导轨','机械','text',NULL,0,1,'[]','{}',60,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-terminal_accessory-flammability','cat-terminal','flammability','阻燃等级','材料','text',NULL,0,1,'[]','{}',70,'','active');
INSERT OR IGNORE INTO product_categories (id,code,name,discipline,applicable_systems_json,icon,description,status) VALUES ('cat-warning-light','WARNING_LIGHT','警示灯 / 声光报警','Controls / Safety','["CTRL","FIRE","SGAS","CDS","HUP"]','◉','多层警示灯、蜂鸣器、声光报警器与状态指示。','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-warning_light-lightType','cat-warning-light','lightType','光源类型','功能','text',NULL,1,1,'[]','{}',10,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-warning_light-tierCount','cat-warning-light','tierCount','层数','结构','number','tier',1,1,'[]','{"min":1}',20,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-warning_light-colors','cat-warning-light','colors','灯罩颜色组合','功能','text',NULL,1,1,'[]','{}',30,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-warning_light-buzzer','cat-warning-light','buzzer','蜂鸣器','功能','boolean',NULL,0,1,'[]','{}',40,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-warning_light-mountingType','cat-warning-light','mountingType','安装方式','机械','text',NULL,0,1,'[]','{}',50,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-warning_light-soundLevel','cat-warning-light','soundLevel','声压级','性能','number','dB',0,1,'[]','{}',60,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-warning_light-flashRate','cat-warning-light','flashRate','闪烁频率','性能','text',NULL,0,1,'[]','{}',70,'','active');
INSERT OR IGNORE INTO product_categories (id,code,name,discipline,applicable_systems_json,icon,description,status) VALUES ('cat-chiller-hx','CHILLER_HEAT_EXCHANGER','冷机 / 换热器 / 冷却塔','Mechanical','["CHW","PCW"]','❄','冷水机组、板式换热器、冷却塔和热回收设备。','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-chiller_heat_exchanger-equipmentType','cat-chiller-hx','equipmentType','设备类型','分类','text',NULL,1,1,'[]','{}',10,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-chiller_heat_exchanger-capacity','cat-chiller-hx','capacity','制冷 / 换热能力','性能','number','kW/RT',1,1,'[]','{}',20,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-chiller_heat_exchanger-designFlow','cat-chiller-hx','designFlow','设计流量','性能','number','m³/h',0,1,'[]','{}',30,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-chiller_heat_exchanger-enteringLeavingTemp','cat-chiller-hx','enteringLeavingTemp','进出水温度','性能','text','°C',1,1,'[]','{}',40,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-chiller_heat_exchanger-cop','cat-chiller-hx','cop','COP / 能效','性能','number',NULL,0,1,'[]','{}',50,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-chiller_heat_exchanger-refrigerant','cat-chiller-hx','refrigerant','制冷剂','工质','text',NULL,0,1,'[]','{}',60,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-chiller_heat_exchanger-heatTransferMaterial','cat-chiller-hx','heatTransferMaterial','换热面材质','材料','text',NULL,0,1,'[]','{}',70,'','active');
INSERT OR IGNORE INTO product_categories (id,code,name,discipline,applicable_systems_json,icon,description,status) VALUES ('cat-tank-vessel','TANK_VESSEL_SKID','罐体 / 容器 / Skid','Mechanical / Process','["SGAS","BSGS","CDS","HUP","CDA","PCW","CHW","UPW","WWT","EXH","FIRE"]','▱','储罐、压力容器、缓冲罐、供应柜和成套 Skid。','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-tank_vessel_skid-equipmentType','cat-tank-vessel','equipmentType','设备类型','分类','text',NULL,1,1,'[]','{}',10,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-tank_vessel_skid-volume','cat-tank-vessel','volume','有效容积','容量','number','L/m³',1,1,'[]','{}',20,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-tank_vessel_skid-designCode','cat-tank-vessel','designCode','设计规范','设计','text',NULL,1,1,'[]','{}',30,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-tank_vessel_skid-shellMaterial','cat-tank-vessel','shellMaterial','壳体材质','材料','text',NULL,1,1,'[]','{}',40,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-tank_vessel_skid-liningMaterial','cat-tank-vessel','liningMaterial','内衬材质','材料','text',NULL,0,1,'[]','{}',50,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-tank_vessel_skid-nozzleSchedule','cat-tank-vessel','nozzleSchedule','接口 / Nozzle 表','接口','text',NULL,0,1,'[]','{}',60,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-tank_vessel_skid-insulation','cat-tank-vessel','insulation','保温 / 伴热','机械','text',NULL,0,1,'[]','{}',70,'','active');
INSERT OR IGNORE INTO product_categories (id,code,name,discipline,applicable_systems_json,icon,description,status) VALUES ('cat-general','GENERAL_PRODUCT','其他自定义产品','Multi-discipline','["SGAS","CDS","HUP","BSGS","CDA","PCW","CHW","CR","UPW","WWT","EXH","FIRE","CTRL"]','＋','尚未归类的产品；管理员可继续新增专用分类和字段。','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-general_product-ratedCapacity','cat-general','ratedCapacity','额定能力','性能','text',NULL,0,1,'[]','{}',10,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-general_product-construction','cat-general','construction','结构形式','结构','text',NULL,0,1,'[]','{}',20,'','active');
INSERT OR IGNORE INTO product_parameter_definitions (id,category_id,key,label,group_name,data_type,unit,required,comparable,options_json,validation_json,sort_order,help_text,status) VALUES ('param-general_product-customRequirement','cat-general','customRequirement','专用工程参数','项目要求','text',NULL,0,1,'[]','{}',30,'','active');
INSERT OR IGNORE INTO catalog_products (id,category_id,manufacturer,brand,product_code,product_name,series,model,description,applicable_systems_json,media_json,min_temperature_c,max_temperature_c,connection_standard,wetted_materials_json,surface_finish,cleanliness_grade,supply_voltage,signal_protocol,ingress_protection,specifications_json,source_document,source_url,source_page,revision,status) VALUES ('prod-aptech-ap1210','cat-regulator','Advanced Pressure Technology','APTech','AP1210SM-2PW-FV8-FV8-HF','高纯单级调压阀','AP1200','AP1210SM 2PW FV8 FV8 HF','由本地产品型录建立的待复核主档','["SGAS","HUP"]','["Specialty Gas"]',NULL,NULL,'Face seal / configuration code','["316L VAR","Ni-Cr-Mo alloy","PCTFE"]','Electropolished option','UHP',NULL,NULL,NULL,'{"regulationType":"single_stage","inletPressureRating":20.7,"outletPressureRange":"依弹簧与订货代码","seatMaterial":"PCTFE"}','调压阀-一类-APTECH-AP1210SM 2PW FV8 FV8 HF.pdf',NULL,NULL,'CATALOG-DRAFT-1','draft');
INSERT OR IGNORE INTO catalog_products (id,category_id,manufacturer,brand,product_code,product_name,series,model,description,applicable_systems_json,media_json,min_temperature_c,max_temperature_c,connection_standard,wetted_materials_json,surface_finish,cleanliness_grade,supply_voltage,signal_protocol,ingress_protection,specifications_json,source_document,source_url,source_page,revision,status) VALUES ('prod-rotarex-rx3210','cat-regulator','Rotarex','Rotarex','RX3210VV4W64F4M4M4FL109','超高纯调压阀','RX3000 / RX3200','RX3210VV4W64F4M4M4FL109','由本地产品型录建立的待复核主档','["SGAS","HUP"]','["UHP Gas"]',NULL,NULL,NULL,'["316L","316L VAR","PCTFE","Hastelloy"]',NULL,'ISO 4 cleanroom assembled',NULL,NULL,NULL,'{"regulationType":"single_stage","outletPressureRange":"依型号代码","seatMaterial":"PCTFE"}','调压阀-一类-Rotarex-RX3210VV4W64F4M4M4FL109.pdf',NULL,NULL,'CATALOG-DRAFT-1','draft');
INSERT OR IGNORE INTO catalog_products (id,category_id,manufacturer,brand,product_code,product_name,series,model,description,applicable_systems_json,media_json,min_temperature_c,max_temperature_c,connection_standard,wetted_materials_json,surface_finish,cleanliness_grade,supply_voltage,signal_protocol,ingress_protection,specifications_json,source_document,source_url,source_page,revision,status) VALUES ('prod-swagelok-cw4','cat-check-bellows','Swagelok Company','Swagelok','6L-CW4VR4','高纯止回阀','CW','6L-CW4VR4','由本地产品型录建立的待复核主档','["SGAS","BSGS","HUP"]','["UHP Gas"]',NULL,NULL,'VCR compatible face seal','["316L stainless steel"]',NULL,NULL,NULL,NULL,NULL,'{"valveType":"check","crackingPressure":"依订货弹簧范围","sealMaterial":"依订货代码","flowDirection":"unidirectional"}','5、Check valve-一类-Swagelok--6L-CW4VR4.pdf','https://www.swagelok.com/downloads/webcatalogs/EN/MS-01-176.PDF',NULL,'CATALOG-DRAFT-1','draft');
INSERT OR IGNORE INTO catalog_products (id,category_id,manufacturer,brand,product_code,product_name,series,model,description,applicable_systems_json,media_json,min_temperature_c,max_temperature_c,connection_standard,wetted_materials_json,surface_finish,cleanliness_grade,supply_voltage,signal_protocol,ingress_protection,specifications_json,source_document,source_url,source_page,revision,status) VALUES ('prod-aptech-ap74100','cat-diaphragm-valve','Advanced Pressure Technology','APTech','AP74100SM-MV4-FV4','高纯隔膜阀','AP7400','AP74100SM MV4 FV4','由本地产品型录建立的待复核主档','["SGAS","HUP"]','["Specialty Gas"]',NULL,NULL,NULL,'["316L VAR","PCTFE"]',NULL,'UHP',NULL,NULL,NULL,'{"actuation":"manual","seatMaterial":"PCTFE","diaphragmMaterial":"Metal diaphragm"}','4、EFS-一类-APTECH-AP74100SM MV4 FV4.pdf',NULL,NULL,'CATALOG-DRAFT-1','draft');
INSERT OR IGNORE INTO catalog_products (id,category_id,manufacturer,brand,product_code,product_name,series,model,description,applicable_systems_json,media_json,min_temperature_c,max_temperature_c,connection_standard,wetted_materials_json,surface_finish,cleanliness_grade,supply_voltage,signal_protocol,ingress_protection,specifications_json,source_document,source_url,source_page,revision,status) VALUES ('prod-pall-glp24','cat-purifier-filter','Pall Corporation','Pall','GLP24HCLPFVMM8','高纯气体净化器','GLP','GLP24HCLPFVMM8','由本地产品型录建立的待复核主档','["SGAS","BSGS"]','["HCl service / catalog verification required"]',NULL,NULL,'Model code dependent','["316L electropolished housing"]',NULL,NULL,NULL,NULL,NULL,'{"gasFamily":"Process gas","removalContaminants":"Moisture, oxygen and trace impurities","mediaMaterial":"Reactive purification media"}','Purifier-一类-PALL-GLP24HCLPFVMM8.pdf','https://www.pall.com/en/microelectronics/semiconductor/process-gas-purification.html',NULL,'CATALOG-DRAFT-1','draft');
INSERT OR IGNORE INTO catalog_products (id,category_id,manufacturer,brand,product_code,product_name,series,model,description,applicable_systems_json,media_json,min_temperature_c,max_temperature_c,connection_standard,wetted_materials_json,surface_finish,cleanliness_grade,supply_voltage,signal_protocol,ingress_protection,specifications_json,source_document,source_url,source_page,revision,status) VALUES ('prod-entegris-gpus300','cat-purifier-filter','Entegris, Inc.','Entegris','GPUS300FIX04R00CA','点位气体净化器','GPU','GPUS300FIX04R00CA','由本地产品型录建立的待复核主档','["SGAS","HUP"]','["Semiconductor process gas"]',NULL,NULL,NULL,'[]',NULL,NULL,NULL,NULL,NULL,'{"gasFamily":"Process gas","removalContaminants":"Trace molecular contaminants"}','Purifier-一类-Entegris-GPUS300FIX04R00CA.pdf','https://www.entegris.com/shop/en/USD/products/gas-filtration-and-purification/gas-purifiers/GPS8-Nitrogen-Gas-Purifiers/p/GPS8NitrogenGasPurifiers',NULL,'CATALOG-DRAFT-1','draft');
INSERT OR IGNORE INTO catalog_products (id,category_id,manufacturer,brand,product_code,product_name,series,model,description,applicable_systems_json,media_json,min_temperature_c,max_temperature_c,connection_standard,wetted_materials_json,surface_finish,cleanliness_grade,supply_voltage,signal_protocol,ingress_protection,specifications_json,source_document,source_url,source_page,revision,status) VALUES ('prod-entegris-wg3','cat-purifier-filter','Entegris, Inc.','Entegris','WG3NS6RR2','高纯气体过滤器','WG','WG3NS6RR2','由本地产品型录建立的待复核主档','["SGAS","BSGS","HUP"]','["UHP Gas"]',NULL,NULL,NULL,'["316L stainless steel"]',NULL,NULL,NULL,NULL,NULL,'{"gasFamily":"UHP gas","removalContaminants":"Particles","mediaMaterial":"Catalog-defined membrane"}','Filter 一类-Entegris-WG3NS6RR2 .pdf',NULL,NULL,'CATALOG-DRAFT-1','draft');
INSERT OR IGNORE INTO catalog_products (id,category_id,manufacturer,brand,product_code,product_name,series,model,description,applicable_systems_json,media_json,min_temperature_c,max_temperature_c,connection_standard,wetted_materials_json,surface_finish,cleanliness_grade,supply_voltage,signal_protocol,ingress_protection,specifications_json,source_document,source_url,source_page,revision,status) VALUES ('prod-wika-23015','cat-pressure-instrument','WIKA Alexander Wiegand SE & Co. KG','WIKA','230.15','UHP 不锈钢压力表','230','230.15','由本地产品型录建立的待复核主档','["SGAS","BSGS","HUP"]','["High-purity gas and liquid"]','-40','100','VCR compatible face seal','["316L stainless steel"]','Ra ≤ 0.25 µm process connection','UHP',NULL,NULL,'IP54','{"instrumentType":"gauge","measuringRange":"0…1 to 0…400 bar","accuracy":"ASME Grade A/B by size","processConnection":"VCR compatible","displayDiameter":50,"heliumLeakRate":"Helium leak tested"}','6、Pressure Gauge-一类-WIKA- 230.15.pdf','https://www.wika.com/media/Data-sheets/Pressure/Pressure-gauges/ds_pm0220_en_co.pdf','1-3','CATALOG-DRAFT-1','draft');
INSERT OR IGNORE INTO catalog_products (id,category_id,manufacturer,brand,product_code,product_name,series,model,description,applicable_systems_json,media_json,min_temperature_c,max_temperature_c,connection_standard,wetted_materials_json,surface_finish,cleanliness_grade,supply_voltage,signal_protocol,ingress_protection,specifications_json,source_document,source_url,source_page,revision,status) VALUES ('prod-nagano-zt11','cat-pressure-instrument','Nagano Keiki Co., Ltd.','Nagano','ZT11-Y02-FVCR','高纯压力变送器','ZT11','ZT11-Y02 FVCR','由本地产品型录建立的待复核主档','["SGAS","BSGS","HUP"]','["UHP Gas"]',NULL,NULL,'FVCR','["SUS316L wetted parts"]','EP / GP / UC options','High purity',NULL,NULL,NULL,'{"instrumentType":"transmitter","measuringRange":"依型号代码","outputSignal":"依型号代码","processConnection":"FVCR","heliumLeakRate":"Catalog specified"}','6、PT-一类-Nagano-ZT11-Y02 FVCR .pdf',NULL,NULL,'CATALOG-DRAFT-1','draft');
INSERT OR IGNORE INTO catalog_products (id,category_id,manufacturer,brand,product_code,product_name,series,model,description,applicable_systems_json,media_json,min_temperature_c,max_temperature_c,connection_standard,wetted_materials_json,surface_finish,cleanliness_grade,supply_voltage,signal_protocol,ingress_protection,specifications_json,source_document,source_url,source_page,revision,status) VALUES ('prod-siemens-hmi','cat-hmi-control','Siemens AG','Siemens','6AV2123-2JB03-0AX0','SIMATIC HMI 面板','SIMATIC HMI','6AV2123-2JB03-0AX0','由本地产品型录建立的待复核主档','["CTRL","SGAS","CDS","UPW","WWT","EXH","FIRE"]','[]',NULL,NULL,NULL,'[]',NULL,NULL,'24 V DC / catalog rating','PROFINET / industrial communication',NULL,'{"deviceType":"HMI","displaySize":9,"resolution":"800 × 480 class / verify exact MLFB datasheet","interfaces":"Industrial Ethernet / model dependent","engineeringSoftware":"WinCC / TIA Portal","mounting":"Panel mount"}','6、HMI-一类-Siemens-S6AV21232JB030AX0.pdf','https://www.siemens.com/en-us/products/simatic-hmi/panels/',NULL,'CATALOG-DRAFT-1','draft');
INSERT OR IGNORE INTO catalog_products (id,category_id,manufacturer,brand,product_code,product_name,series,model,description,applicable_systems_json,media_json,min_temperature_c,max_temperature_c,connection_standard,wetted_materials_json,surface_finish,cleanliness_grade,supply_voltage,signal_protocol,ingress_protection,specifications_json,source_document,source_url,source_page,revision,status) VALUES ('prod-honeywell-fsl100','cat-fire-detector','Honeywell International Inc.','Honeywell','FSL-100','火焰探测器','FSL','FSL-100','由本地产品型录建立的待复核主档','["FIRE","SGAS","CDS","HUP"]','[]',NULL,NULL,NULL,'[]',NULL,NULL,NULL,'4–20 mA / relay / model configuration',NULL,'{"detectorType":"Flame detector","detectionRange":"依火源类型与型录","analogOutput":"4–20 mA","relayOutputs":"Alarm / fault","selfTest":true}','3-8-1-1 Honeywell-FSL-100.pdf','https://buildings.honeywell.com/us/en/products/by-category/fire-life-safety/sensors-and-detectors/flame-detectors/fs7-fire-and-flame-detector',NULL,'CATALOG-DRAFT-1','draft');
INSERT OR IGNORE INTO catalog_products (id,category_id,manufacturer,brand,product_code,product_name,series,model,description,applicable_systems_json,media_json,min_temperature_c,max_temperature_c,connection_standard,wetted_materials_json,surface_finish,cleanliness_grade,supply_voltage,signal_protocol,ingress_protection,specifications_json,source_document,source_url,source_page,revision,status) VALUES ('prod-senseware-uvir','cat-fire-detector','Sense-WARE','Sense-WARE','UV-IR-210-1','UV/IR 火焰探测器','UV/IR','UV-IR-210-1','由本地产品型录建立的待复核主档','["FIRE","SGAS","CDS","HUP"]','[]',NULL,NULL,NULL,'[]',NULL,NULL,NULL,NULL,NULL,'{"detectorType":"UV/IR","detectionRange":"依型录","selfTest":true}','3-8-2-1 Senseware-UV-IR-210-1.pdf',NULL,NULL,'CATALOG-DRAFT-1','draft');
