import { and, desc, eq } from "drizzle-orm";
import { getDb } from "@/db";
import { attachments, projectProductRequirements, technicalSpecExtractions } from "@/db/schema";
import { ApiError, errorResponse } from "@/lib/api";
import { writeAudit } from "@/lib/audit";
import { assertAuthenticated, assertProjectAccess, authorize } from "@/lib/auth";

export async function GET(request:Request){try{const principal=await authorize(request,"equipment:read");const url=new URL(request.url);const projectId=url.searchParams.get("projectId")??"";const requirementId=url.searchParams.get("requirementId")??"";if(!projectId)throw new ApiError(400,"项目不能为空","INVALID_INPUT");assertProjectAccess(principal,projectId);const conditions=[eq(technicalSpecExtractions.projectId,projectId)];if(requirementId)conditions.push(eq(technicalSpecExtractions.requirementId,requirementId));const rows=await getDb().select().from(technicalSpecExtractions).where(and(...conditions)).orderBy(desc(technicalSpecExtractions.createdAt)).limit(100);return Response.json({extractions:rows})}catch(error){return errorResponse(error)}}

export async function POST(request:Request){try{const principal=await authorize(request,"equipment:validate");assertAuthenticated(principal);const body=await request.json() as {projectId?:string;requirementId?:string;attachmentId?:string;fileName?:string;parserType?:string;pageCount?:number;extracted?:Record<string,unknown>;confidence?:Record<string,number>;textExcerpt?:string;confirmed?:boolean};const projectId=body.projectId?.trim()??"";if(!projectId||!body.requirementId||!body.attachmentId)throw new ApiError(400,"项目、选型要求和附件不能为空","INVALID_INPUT");assertProjectAccess(principal,projectId,true);const db=getDb();const [requirement]=await db.select().from(projectProductRequirements).where(and(eq(projectProductRequirements.id,body.requirementId),eq(projectProductRequirements.projectId,projectId))).limit(1);const [attachment]=await db.select().from(attachments).where(and(eq(attachments.id,body.attachmentId),eq(attachments.projectId,projectId))).limit(1);if(!requirement||!attachment)throw new ApiError(404,"选型要求或规格书附件不存在","NOT_FOUND");const row={id:crypto.randomUUID(),projectId,requirementId:requirement.id,attachmentId:attachment.id,fileName:body.fileName||attachment.fileName,parserType:body.parserType||"manual",pageCount:Math.max(0,Math.round(Number(body.pageCount)||0)),extractedJson:JSON.stringify(body.extracted??{}),confidenceJson:JSON.stringify(body.confidence??{}),textExcerpt:String(body.textExcerpt??"").slice(0,4000),status:body.confirmed?"confirmed":"needs_review",confirmedBy:body.confirmed?principal.email:null,confirmedAt:body.confirmed?new Date().toISOString():null};await db.insert(technicalSpecExtractions).values(row);await writeAudit(request,principal,{projectId,action:"technical_spec.extract",entityType:"projectProductRequirements",entityId:requirement.id,after:{extractionId:row.id,attachmentId:attachment.id,parserType:row.parserType,status:row.status,fields:Object.keys(body.extracted??{})}});return Response.json({extraction:row},{status:201})}catch(error){return errorResponse(error)}}