"use client";

import { useEffect, useMemo, useState } from "react";
import { downloadCsv, openMasterData } from "@/lib/client-actions";

type Notify = (message: string) => void;
type ComponentRow = { id:string; equipmentModelId:string; componentCode:string; componentName:string; function:string; medium:string; allowedMaterialsJson:string; requiredFinish:string; requiredCleanliness:string; designPressureMpa:number; designTemperatureC:number; connectionStandard:string; nominalSize:string; quantity:number; criticality:string };
type PortRow = { id:string; portCode:string; service:string; direction:string; connectionStandard:string; nominalSize:string; pressureRatingMpa:number; temperatureRatingC:number; faceToFaceMm:number|null };
type ModelRow = { id:string; code:string; name:string; category:string; revision:string; designStandard:string; factoryCode:string; factoryName:string; country:string; qualityStatus:string; components:ComponentRow[]; ports:PortRow[] };
type MaterialRow = { id:string; code:string; manufacturer:string; name:string; grade:string; baseMaterial:string; surfaceFinish:string; cleanlinessGrade:string; maxPressureMpa:number; minTemperatureC:number; maxTemperatureC:number; certificationsJson:string };
type TechnicalRuleRow = { ruleCode:string; serviceName:string; mediumCodesJson:string; approvalRuleCode:string|null; requiredGrade:string; requiredFinish:string; fittingStandard:string; valveType:string; flexibleTubePolicy:string; doubleContainment:boolean; nominalSizesJson:string; restrictions:string; sourceDocument:string; sourcePages:string; sourceClause:string };
type BrandRuleRow = { ruleCode:string; categoryCode:string; itemName:string; requiredGrade:string; allowedBrandsJson:string; restrictions:string; sourceDocument:string; sourcePage:string };
type RuleResult = { ruleCode:string; category:string; severity:string; status:string; expected:string; actual:string; message:string };
type Validation = { runId:string; status:string; score:number; fatalCount:number; warningCount:number; results:RuleResult[] };

const fallbackMaterials:MaterialRow[]=[
  {id:"mat-316l-ep",code:"M-316L-EP",manufacturer:"FabFlow Approved",name:"316L EP 管件",grade:"316L",baseMaterial:"SS",surfaceFinish:"EP",cleanlinessGrade:"UHP",maxPressureMpa:8.3,minTemperatureC:-40,maxTemperatureC:180,certificationsJson:'["EN10204 3.1","SEMI F20"]'},
  {id:"mat-pfa-hp",code:"M-PFA-HP",manufacturer:"FabFlow Approved",name:"HP PFA 接液件",grade:"PFA",baseMaterial:"PFA",surfaceFinish:"HP PFA",cleanlinessGrade:"HP",maxPressureMpa:1.0,minTemperatureC:-20,maxTemperatureC:120,certificationsJson:'["SEMI F57","COC"]'},
  {id:"mat-pvdf-hp",code:"M-PVDF-HP",manufacturer:"FabFlow Approved",name:"HP PVDF 接液件",grade:"PVDF",baseMaterial:"PVDF",surfaceFinish:"HP PVDF",cleanlinessGrade:"UPW",maxPressureMpa:1.6,minTemperatureC:0,maxTemperatureC:95,certificationsJson:'["SEMI F57","ASTM D3222"]'},
];
const fallbackModels:ModelRow[]=[{
  id:"eq-gc-04",code:"GC-VMB-04",name:"四瓶位特气 VMB 柜",category:"Gas Delivery",revision:"Rev.C",designStandard:"SEMI S2 / NFPA 55",factoryCode:"FCT-001",factoryName:"Global Gas Equipment Works",country:"CN",qualityStatus:"qualified",
  components:[
    {id:"cmp-gc-vcr",equipmentModelId:"eq-gc-04",componentCode:"GC-INT-001",componentName:"内部高压主管",function:"特气分配",medium:"SiH4",allowedMaterialsJson:'["316L"]',requiredFinish:"EP",requiredCleanliness:"UHP",designPressureMpa:1.0,designTemperatureC:60,connectionStandard:"VCR",nominalSize:'1/4”',quantity:4,criticality:"A"},
    {id:"cmp-gc-valve",equipmentModelId:"eq-gc-04",componentCode:"GC-INT-002",componentName:"气动隔膜阀",function:"隔离与联锁切断",medium:"SiH4",allowedMaterialsJson:'["316L"]',requiredFinish:"EP",requiredCleanliness:"UHP",designPressureMpa:1.0,designTemperatureC:60,connectionStandard:"VCR",nominalSize:'1/4”',quantity:8,criticality:"A"},
  ],
  ports:[{id:"port-gc-p1",portCode:"P-GAS-01",service:"SiH4",direction:"OUT",connectionStandard:"VCR",nominalSize:'1/4”',pressureRatingMpa:8.3,temperatureRatingC:120,faceToFaceMm:35}],
}];

export function EquipmentFactoryPage({notify:parentNotify}:{notify:Notify}){
  const notify:Notify=(message)=>{
    parentNotify(message);
  };
  const [models,setModels]=useState<ModelRow[]>(fallbackModels); const [materials,setMaterials]=useState<MaterialRow[]>(fallbackMaterials);
  const [technicalRules,setTechnicalRules]=useState<TechnicalRuleRow[]>([]); const [brandRules,setBrandRules]=useState<BrandRuleRow[]>([]);
  const [modelId,setModelId]=useState(fallbackModels[0].id); const [componentId,setComponentId]=useState(fallbackModels[0].components[0].id); const [materialCode,setMaterialCode]=useState(fallbackMaterials[0].code); const [portId,setPortId]=useState(fallbackModels[0].ports[0].id);
  const [medium,setMedium]=useState("SiH4"); const [pressure,setPressure]=useState(0.72); const [temperature,setTemperature]=useState(35); const [connection,setConnection]=useState("VCR"); const [size,setSize]=useState('1/4”'); const [doubleContainment,setDoubleContainment]=useState<"single"|"double">("single"); const [flexibleTube,setFlexibleTube]=useState<"none"|"PFA451HP">("none");
  const [validation,setValidation]=useState<Validation|null>(null); const [loading,setLoading]=useState(false); const [backend,setBackend]=useState("正在连接权威数据库"); const [role,setRole]=useState("—"); const [tab,setTab]=useState("内部材料");
  const model=useMemo(()=>models.find(x=>x.id===modelId)??models[0],[models,modelId]); const component=model?.components.find(x=>x.id===componentId)??model?.components[0]; const port=model?.ports.find(x=>x.id===portId)??model?.ports[0];
  const technicalRule=useMemo(()=>technicalRules.find(rule=>{try{return (JSON.parse(rule.mediumCodesJson) as string[]).some(x=>x.toLowerCase()===medium.toLowerCase())}catch{return false}})??null,[technicalRules,medium]);
  const brandRule=useMemo(()=>technicalRule?.approvalRuleCode?brandRules.find(rule=>rule.ruleCode===technicalRule.approvalRuleCode)??null:null,[technicalRule,brandRules]);
  const selectedMaterial=useMemo(()=>materials.find(x=>x.code===materialCode)??materials[0],[materials,materialCode]);
  const brandAllowed=useMemo(()=>{if(!selectedMaterial||!brandRule)return null;try{return (JSON.parse(brandRule.allowedBrandsJson) as string[]).some(x=>selectedMaterial.manufacturer.toLowerCase().includes(x.toLowerCase())||x.toLowerCase().includes(selectedMaterial.manufacturer.toLowerCase()))}catch{return false}},[selectedMaterial,brandRule]);

  useEffect(()=>{fetch("/api/equipment/catalog").then(async res=>{if(!res.ok)throw new Error((await res.json()).error);return res.json()}).then(data=>{if(data.models?.length){setModels(data.models);setMaterials(data.materials);setTechnicalRules(data.technicalRules??[]);setBrandRules(data.brandRules??[]);setModelId(data.models[0].id);setComponentId(data.models[0].components[0]?.id??"");setPortId(data.models[0].ports[0]?.id??"");const preferred=data.materials?.find((x:MaterialRow)=>x.manufacturer!=="FabFlow Approved");if(preferred)setMaterialCode(preferred.code);setRole(data.principal?.roles?.join(" / ")??"viewer");setBackend("D1 权威数据库已连接 · 技术文件与品牌表已加载")}}).catch(()=>setBackend("演示数据 · 发布后需工作区身份"))},[]);
  // eslint-disable-next-line react-hooks/set-state-in-effect, react-hooks/exhaustive-deps
  useEffect(()=>{if(!model)return; const c=model.components[0]; const p=model.ports[0]; if(c){setComponentId(c.id);setMedium(c.medium);setConnection(c.connectionStandard);setSize(c.nominalSize);setPressure(Math.min(c.designPressureMpa,.72));setTemperature(Math.min(c.designTemperatureC,35))}if(p)setPortId(p.id);setValidation(null)},[modelId]);
  // eslint-disable-next-line react-hooks/set-state-in-effect, react-hooks/exhaustive-deps
  useEffect(()=>{if(!component)return;setMedium(component.medium);setConnection(component.connectionStandard);setSize(component.nominalSize);setValidation(null)},[componentId]);

  const validate=async()=>{if(!model||!component)return;setLoading(true);try{const res=await fetch("/api/equipment/validate",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({projectId:"proj-fab2a",equipmentModelId:model.id,componentId:component.id,portId:port?.id,medium,selectedMaterialCode:materialCode,connectionStandard:connection,nominalSize:size,operatingPressureMpa:pressure,operatingTemperatureC:temperature,doubleContainment,flexibleTube})});const data=await res.json();if(!res.ok)throw new Error(data.error);setValidation(data);notify(data.status==="passed"?"选型校验通过并已写入审计日志":"选型存在不符合项，已形成校验记录")}catch(error){notify(error instanceof Error?error.message:"校验失败")}finally{setLoading(false)}};
  const createApproval=async()=>{if(!validation?.runId)return;const res=await fetch("/api/approvals",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({projectId:"proj-fab2a",workflowType:"material_selection",entityType:"selection_run",entityId:validation.runId,title:`${model.code} · ${component?.componentCode} 材料选型`,steps:["设备工程师","系统负责人","QA/QC","项目经理"]})});notify(res.ok?"材料选型审批已创建":"审批创建失败")};
  const upload=async(file:File)=>{if(!model)return;const form=new FormData();form.append("file",file);form.append("projectId","proj-fab2a");form.append("entityType","equipment_model");form.append("entityId",model.id);form.append("category","vendor_document");const res=await fetch("/api/files",{method:"POST",body:form});const data=await res.json();notify(res.ok?`已保存 ${data.file.fileName}，版本 v${data.file.version}`:data.error??"上传失败")};

  if(!model)return null;
  return <>
    <div className="moduleTop factoryTop"><div><span>EQUIPMENT FACTORY COLLABORATION</span><h2>设备工厂协同与内部材料校验</h2><p>贯通设备厂内部 BOM、项目接口条件和批准材料库，自动判断材料、接口、压力、温度、洁净及文件证据是否满足。</p></div><div className="moduleActions"><button className="softButton" onClick={()=>{downloadCsv("fabflow-equipment-factory-template.csv",["设备厂编码","设备型号编码","部件编码","部件名称","接口标准","公称尺寸","设计压力MPa","设计温度℃","材料牌号","表面处理","清洁等级"],[]);notify("设备厂数据模板已生成")}}>下载设备厂模板</button><button className="primaryButton" onClick={()=>{openMasterData("equipmentFactories");notify("设备厂协同邀请已创建")}}>＋ 邀请设备厂</button></div></div>
    <div className="factoryKpis"><section className="card"><span>接入设备厂</span><b>8<small> 家</small></b><p>{backend}</p></section><section className="card"><span>设备内部物料</span><b>1,428<small> 项</small></b><p>关键 A 类 186 项</p></section><section className="card"><span>接口冻结率</span><b>82<small>%</small></b><p className="amberText">14 个接口待设备厂确认</p></section><section className="card"><span>当前服务端角色</span><b className="roleValue">{role}</b><p>写入、审批均由服务端校验</p></section></div>
    <div className="factoryTabs">{[["内部材料","BOM & Material"],["设备接口","Ports & Hook-up"],["合规判定","Validation"],["文件与审批","Evidence"]].map(([x,en])=><button key={x} className={tab===x?"active":""} onClick={()=>setTab(x)}><i>{x==="内部材料"?"▤":x==="设备接口"?"⑂":x==="合规判定"?"✓":"▧"}</i><span>{x}</span><small>{en}</small></button>)}</div>
    <div className="factoryLayout">
      <aside className="card modelSelector"><div className="factoryHead"><div><span>FACTORY EQUIPMENT</span><h3>设备型号与版本</h3></div></div>{models.map(x=><button className={modelId===x.id?"active":""} key={x.id} onClick={()=>setModelId(x.id)}><i>{x.category.includes("Gas")?"G":x.category.includes("Wet")?"W":"E"}</i><span><code>{x.code}</code><b>{x.name}</b><small>{x.factoryName} · {x.revision}</small></span><em>{x.qualityStatus==="qualified"?"已准入":"关注"}</em></button>)}</aside>
      <main className="card factoryWorkspace">
        <div className="factoryHead"><div><span>{model.factoryCode} · {model.designStandard}</span><h3>{model.name}</h3><p>{model.factoryName} · {model.country} · 设备版本 {model.revision}</p></div><button onClick={()=>{openMasterData("equipmentModels",model.code);notify("设备厂版本差异已打开")}}>版本差异</button></div>
        {tab==="内部材料"&&<div className="internalBom"><div className="bomHeader"><span>内部位号 / 部件</span><span>介质与功能</span><span>设计参数</span><span>要求材料 / 表面</span><span>数量</span></div>{model.components.map(c=><button key={c.id} className={componentId===c.id?"active":""} onClick={()=>setComponentId(c.id)}><i className={c.criticality==="A"?"critical":""}>{c.criticality}</i><span><code>{c.componentCode}</code><b>{c.componentName}</b></span><span><b>{c.medium}</b><small>{c.function}</small></span><span><b>{c.designPressureMpa} MPa</b><small>{c.designTemperatureC} °C</small></span><span><b>{JSON.parse(c.allowedMaterialsJson).join(" / ")}</b><small>{c.requiredFinish} · {c.requiredCleanliness}</small></span><strong>× {c.quantity}</strong></button>)}</div>}
        {tab==="设备接口"&&<div className="portBoard"><div className="portHeader"><span>设备口</span><span>服务 / 方向</span><span>连接制式</span><span>额定参数</span><span>对接判断</span></div>{model.ports.map(p=><button key={p.id} className={portId===p.id?"active":""} onClick={()=>{setPortId(p.id);setConnection(p.connectionStandard);setSize(p.nominalSize)}}><code>{p.portCode}</code><span><b>{p.service}</b><small>{p.direction}</small></span><span><b>{p.connectionStandard}</b><small>{p.nominalSize}</small></span><span><b>{p.pressureRatingMpa} MPa</b><small>{p.temperatureRatingC} °C · F/F {p.faceToFaceMm??"—"} mm</small></span><em>{p.connectionStandard===connection&&p.nominalSize===size?"可直接连接":"需要转换"}</em></button>)}</div>}
        {tab==="合规判定"&&<ValidationPanel validation={validation}/>} 
        {tab==="文件与审批"&&<div className="evidencePanel"><section><span>VENDOR DOCUMENT REGISTER</span><h3>设备厂文件证据</h3>{["设备内部 BOM 与材质清单","接口图 / GA / Hook-up Matrix","材料证明与表面处理报告","FAT / ITP / 功能测试记录"].map((x,i)=><p key={x}><i className={i<2?"done":""}>{i<2?"✓":"!"}</i><span><b>{x}</b><small>{i<2?"D1 元数据 + R2 文件已关联":"设备厂待上传"}</small></span></p>)}<label className="uploadButton">上传设备厂文件<input type="file" onChange={e=>e.target.files?.[0]&&upload(e.target.files[0])}/></label></section><section><span>APPROVAL GATE</span><h3>材料选型发布</h3><p>审批路径：设备工程师 → 系统负责人 → QA/QC → 项目经理</p><div className="approvalGate"><b>{validation?validation.score:"—"}</b><small>当前校验分</small></div><button className="fullPrimary" disabled={!validation?.runId} onClick={createApproval}>{validation?.runId?"提交材料选型审批":"先完成一次校验"}</button></section></div>}
      </main>
      <aside className="card selectionInspector"><div className="factoryHead"><div><span>SELECTION INPUT</span><h3>选型条件</h3></div><i className="live"/></div><label><span>内部部件</span><select value={componentId} onChange={e=>setComponentId(e.target.value)}>{model.components.map(c=><option value={c.id} key={c.id}>{c.componentCode} · {c.componentName}</option>)}</select></label><label><span>介质</span><input value={medium} onChange={e=>setMedium(e.target.value)}/></label><label><span>候选材料</span><select value={materialCode} onChange={e=>setMaterialCode(e.target.value)}>{materials.map(m=><option value={m.code} key={m.id}>{m.code} · {m.manufacturer} · {m.grade} · {m.surfaceFinish}</option>)}</select></label>{technicalRule&&<div className={`ruleEvidence ${brandAllowed===false?"blocked":brandAllowed===true?"approved":""}`}><span><b>{technicalRule.serviceName}</b><small>技术文件 {technicalRule.sourceClause} · P{technicalRule.sourcePages}</small></span><em>{technicalRule.requiredGrade} · {technicalRule.requiredFinish} · {technicalRule.fittingStandard}</em>{brandRule&&<small className="brandEvidence">品牌表 {brandRule.ruleCode}：{brandAllowed===true?"已准入":"当前品牌未在准入清单"}</small>}</div>}<div className="inspectorDouble"><label><span>工作压力 MPa</span><input type="number" step="0.01" value={pressure} onChange={e=>setPressure(+e.target.value)}/></label><label><span>工作温度 °C</span><input type="number" value={temperature} onChange={e=>setTemperature(+e.target.value)}/></label></div><div className="inspectorDouble"><label><span>连接制式</span><select value={connection} onChange={e=>setConnection(e.target.value)}>{["VCR","Weld","Flare","Tri-Clamp","Flange"].map(x=><option key={x}>{x}</option>)}</select></label><label><span>接口尺寸</span><select value={size} onChange={e=>setSize(e.target.value)}>{['1/4”','3/8”','1/2”','DN15','DN25'].map(x=><option key={x}>{x}</option>)}</select></label></div><div className="inspectorDouble"><label><span>套管形式</span><select value={doubleContainment} onChange={e=>setDoubleContainment(e.target.value as "single"|"double")}><option value="single">单管</option><option value="double">双套管</option></select></label><label><span>Hookup 软管</span><select value={flexibleTube} onChange={e=>setFlexibleTube(e.target.value as "none"|"PFA451HP")}><option value="none">不使用</option><option value="PFA451HP">PFA451HP</option></select></label></div><button className="validateButton" onClick={validate} disabled={loading}>{loading?"正在执行服务端规则…":"执行材料与接口校验"}<span>→</span></button>{validation&&<div className={`validationSummary ${validation.status}`}><span>{validation.status==="passed"?"✓":"!"}</span><div><b>{validation.status==="passed"?"选型通过":validation.status==="attention"?"带条件通过":"禁止发布"}</b><small>{validation.score} 分 · 致命 {validation.fatalCount} · 警告 {validation.warningCount}</small></div></div>}</aside>
    </div>
  </>;
}

function ValidationPanel({validation}:{validation:Validation|null}){if(!validation)return <div className="emptyValidation"><i>✓</i><h3>等待执行工程校验</h3><p>系统会逐条检查介质兼容、批准材料、表面处理、洁净等级、耐压、温度、连接制式、尺寸和材料证明。</p></div>;return <div className="ruleBoard"><div className="ruleScore"><b>{validation.score}</b><span><strong>{validation.status==="passed"?"全部符合":validation.status==="attention"?"带条件符合":"存在致命不符合"}</strong><small>运行记录 {validation.runId.slice(0,8)} · 已写入 D1 与审计日志</small></span><em>{validation.fatalCount} 致命 / {validation.warningCount} 警告</em></div>{validation.results.map(r=><div className="ruleRow" key={r.ruleCode}><i className={r.status}>{r.status==="pass"?"✓":r.status==="warning"?"!":"×"}</i><span><code>{r.ruleCode} · {r.category}</code><b>{r.message}</b><small>要求：{r.expected} · 实际：{r.actual}</small></span><em className={r.status}>{r.status==="pass"?"符合":r.status==="warning"?"复核":"不符合"}</em></div>)}</div>}
