"use client";

import { useState } from "react";
import { downloadCsv, openMasterData } from "@/lib/client-actions";

type Notify=(message:string)=>void;

const initialProcurement=[
  {id:"LLI-001",item:"UPW Polishing Skid · 40 m³/h",package:"UPW-UTIL-02",vendor:"Kurita / JP",po:"PO-26-01842",promise:"08/12",latest:"08/18",expedite:"供应商周报",status:"关注",impact:"RFC + 4 天",value:4200},
  {id:"LLI-004",item:"六路 Cl₂ VMB Cabinet",package:"GAS-VMB-04",vendor:"Entegris / US",po:"PO-26-01790",promise:"07/30",latest:"08/02",expedite:"现场催交",status:"风险",impact:"FAT 关键路径",value:860},
  {id:"LLI-007",item:"Acid Exhaust Scrubber",package:"EXH-AE-03",vendor:"Dürr / DE",po:"PO-26-01671",promise:"09/05",latest:"09/05",expedite:"正常",status:"正常",impact:"无",value:1280},
  {id:"LLI-011",item:"316L EP Tube · 1/4 / 1/2 inch",package:"MAT-GAS-02",vendor:"Swagelok / SG",po:"PO-26-01902",promise:"07/22",latest:"07/24",expedite:"已到港",status:"正常",impact:"无",value:315},
  {id:"LLI-015",item:"UPW PVDF Diaphragm Valve",package:"UPW-VAL-08",vendor:"Gemu / DE",po:"PO-26-01896",promise:"07/26",latest:"07/31",expedite:"清关协调",status:"关注",impact:"CWP-03",value:188},
];

const receiving=[
  {id:"GRN-0718-04",item:"316L EP Tube · 1,240 m",po:"PO-26-01902",arrival:"07/18",location:"WH-A / Bay 03",qc:"待 IQC",docs:"MTC / CoC 完整",status:"待检"},
  {id:"GRN-0717-02",item:"M5 四组合螺栓 · 9,800 套",po:"PO-26-01874",arrival:"07/17",location:"WH-A / Bin 14",qc:"抽检中",docs:"CoC 缺 1 页",status:"关注"},
  {id:"GRN-0715-01",item:"VMB Cabinet · 4 台",po:"PO-26-01790",arrival:"07/15",location:"Laydown / Zone B",qc:"FAT 记录复核",docs:"Vendor Data 完整",status:"隔离"},
  {id:"GRN-0712-08",item:"PVDF Valve · 48 件",po:"PO-26-01896",arrival:"07/12",location:"WH-B / Rack 08",qc:"IQC 合格",docs:"全套",status:"已放行"},
];

const schedule=[
  {id:"M-01",name:"G3 详细设计发布",owner:"设计管理",date:"07/31",progress:88,status:"关键",offset:0,width:22},
  {id:"M-02",name:"长周期设备 FAT",owner:"采购 / Vendor",date:"08/16",progress:64,status:"关注",offset:19,width:20},
  {id:"M-03",name:"洁净室封闭",owner:"施工管理",date:"09/18",progress:43,status:"正常",offset:36,width:19},
  {id:"M-04",name:"Utility Ready",owner:"调试管理",date:"12/08",progress:26,status:"关键",offset:56,width:18},
  {id:"M-05",name:"RFSU / 运营移交",owner:"运营团队",date:"01/26",progress:12,status:"正常",offset:78,width:17},
];

export function ProgramControlsPage({notify:parentNotify}:{notify:Notify}){
  const notify:Notify=(message)=>{
    if(message.includes("项目控制月报")) downloadCsv("fabflow-program-control-report.csv",["指标","当前值","说明"],[["关键路径浮时","-18 天","Utility Ready 受长周期设备影响"],["采购承诺额","$24.8M","已下单 82%"],["现场到货准时率","91%","较上月 +3.2%"]]);
    if(message.includes("新控制事项")||message.includes("新长周期设备")||message.includes("收货批次")) openMasterData("purchaseOrders");
    parentNotify(message);
  };
  const [tab,setTab]=useState("主计划"); const [procurement,setProcurement]=useState(initialProcurement); const [receipts,setReceipts]=useState(receiving); const [contingency,setContingency]=useState(8);
  const updateProc=(id:string)=>{setProcurement(procurement.map(x=>x.id===id?{...x,expedite:"已升级至项目总监",status:"风险"}:x));notify(`${id} 已升级为项目级催交事项`)};
  const updateReceipt=(id:string)=>{setReceipts(receipts.map(x=>x.id===id?{...x,status:x.status==="待检"?"抽检中":x.status==="抽检中"?"已放行":x.status}:x));notify(`${id} 收货质量状态已更新`)};
  return <>
    <div className="moduleTop controlsTop"><div><span>PROGRAM CONTROLS</span><h2>计划、采购与成本控制</h2><p>用关键路径、长周期设备、到货质量和成本预测控制 FAB 项目能否按期投产</p></div><div className="moduleActions"><button className="softButton" onClick={()=>notify("已生成项目控制月报")}>项目控制月报</button><button className="primaryButton" onClick={()=>notify("新控制事项已创建")}>＋ 新建控制事项</button></div></div>
    <div className="controlKpis"><section className="card"><span>关键路径浮时</span><b>−18<small>天</small></b><p className="redText">Utility Ready 受长周期设备影响</p></section><section className="card"><span>采购承诺额</span><b>$ 24.8<small>M</small></b><p>已下单 82% · 未承诺 $4.6M</p></section><section className="card"><span>长周期设备</span><b>5<small>项</small></b><p className="amberText">2 项交期有偏差</p></section><section className="card"><span>现场到货准时率</span><b>91<small>%</small></b><p>较上月 +3.2%</p></section><section className="card"><span>完工预测偏差</span><b>+1.6<small>%</small></b><p className="greenText">低于管理阈值 3%</p></section>
    </div>
    <div className="controlTabs">{["主计划","长周期采购","到货与质量","成本预测"].map(x=><button key={x} className={tab===x?"active":""} onClick={()=>setTab(x)}><i>{x==="主计划"?"◷":x==="长周期采购"?"▣":x==="到货与质量"?"✓":"◇"}</i><span>{x}</span><small>{x==="主计划"?"Critical Path":x==="长周期采购"?"Expediting":x==="到货与质量"?"Receiving / IQC":"Forecast / Commitment"}</small></button>)}</div>
    {tab==="主计划"&&<ScheduleView notify={notify}/>} 
    {tab==="长周期采购"&&<ProcurementView items={procurement} update={updateProc} notify={notify}/>} 
    {tab==="到货与质量"&&<ReceivingView items={receipts} update={updateReceipt} notify={notify}/>} 
    {tab==="成本预测"&&<CostView contingency={contingency} setContingency={setContingency} notify={notify}/>} 
  </>;
}

function ScheduleView({notify}:{notify:Notify}){
  const [discipline,setDiscipline]=useState("全部专业");
  return <div className="controlSchedule"><section className="card scheduleBoard"><div className="controlsHead"><div><span>MASTER SCHEDULE · IMS</span><h3>关键路径与三个月滚动计划</h3><p>基于 WBS、逻辑关系和实际进度，识别对 Utility Ready 有影响的路径</p></div><div><button className="active">6 周</button><button>3 个月</button><button onClick={()=>notify("已打开基线对比")}>对比基线</button></div></div><div className="scheduleHeader"><span>2026 年 7 月</span><i/><span>8 月</span><i/><span>9 月</span><i/><span>10 月</span></div><div className="scheduleRows">{schedule.map(x=><div className="scheduleRow" key={x.id}><div><code>{x.id}</code><b>{x.name}</b><small>{x.owner}</small></div><div className="scheduleTrack"><span className="today"/><i className={x.status==="关键"?"critical":x.status==="关注"?"attention":""} style={{left:`${x.offset}%`,width:`${x.width}%`}}><em>{x.progress}%</em></i><small>{x.date}</small></div><span className={`scheduleStatus ${x.status==="关键"?"critical":x.status==="关注"?"attention":""}`}>{x.status}</span></div>)}</div><div className="scheduleLegend"><span><i className="critical"/>关键路径</span><span><i className="attention"/>管理关注</span><span><i/>正常路径</span><span><b>今天</b> 2026-07-16</span></div></section><aside className="card pathRisks"><div className="controlsHead"><div><span>PATH RISKS</span><h3>关键路径风险</h3></div></div>{[["长周期 VMB Cabinet","FAT 交期 +3 天","高","LLI-004"],["消防 AHJ 原则审批","尚未取得书面意见","中","RFI-2841"],["洁净室封闭条件","机电综合冲突 6 项","中","CWP-012"]].map(x=><button key={x[0]} onClick={()=>notify(`已打开风险 ${x[3]}`)}><i className={x[2]==="高"?"high":"medium"}>!</i><span><b>{x[0]}</b><small>{x[1]}</small></span><em>{x[2]}</em></button>)}<button className="fullPrimary" onClick={()=>notify("项目风险评审会议已创建")}>发起路径风险评审</button></aside><section className="card lookaheadControls"><div className="controlsHead"><div><span>LOOKAHEAD CONSTRAINTS</span><h3>两周滚动计划约束</h3></div><div className="disciplineFilter">{["全部专业","工艺","厂务","施工","采购"].map(x=><button className={discipline===x?"active":""} onClick={()=>setDiscipline(x)} key={x}>{x}</button>)}</div></div><div className="constraintRows">{[["CWP-GAS-L2-07","气体管线安装包","材料","316L EP 管到货延迟","采购 / K. Tan","07/18"],["CWP-CDS-L1-04","CDS Skid 连接包","设计","基础荷载复核未完成","结构 / L. Wang","07/17"],["CWP-EXH-ROOF-02","屋面酸排风安装包","作业面","防水施工未移交","土建 / H. Xu","07/19"],["CWP-UPW-SUB-03","UPW 回水支管","许可","夜间动火许可待批","施工 / Y. Zhao","07/18"]].map(x=><div key={x[0]}><code>{x[0]}</code><span><b>{x[1]}</b><small>{x[2]} · {x[3]}</small></span><em>{x[4]}</em><time className={x[5]==="07/17"?"redText":""}>{x[5]}</time><button onClick={()=>notify(`约束 ${x[0]} 已分派`)}>分派</button></div>)}</div></section></div>;
}

function ProcurementView({items,update,notify}:{items:typeof initialProcurement;update:(id:string)=>void;notify:Notify}){
  return <><section className="card procurementHeader"><div><span>LONG LEAD ITEM CONTROL</span><h3>长周期设备与催交台账</h3><p>把 PO、Vendor Data、FAT、发运、清关、到货与关键路径绑定在同一条记录上</p></div><div><button>导出催交清单</button><button onClick={()=>notify("催交会议已创建")}>安排供应商会议</button></div></section><section className="card procurementBoard"><div className="procurementToolbar"><div className="searchBox">⌕<input placeholder="搜索 LLI、物料、Vendor、PO…"/></div><div><button>全部状态</button><button>关键路径</button><button onClick={()=>notify("新长周期设备已登记")}>＋ 登记 LLI</button></div></div><div className="procurementTable"><table><thead><tr><th>LLI / 物料</th><th>采购包</th><th>Vendor / PO</th><th>承诺交期</th><th>最新预测</th><th>催交状态</th><th>关键路径影响</th><th>金额 $k</th><th></th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td><code>{x.id}</code><b>{x.item}</b></td><td>{x.package}</td><td><span>{x.vendor}</span><small>{x.po}</small></td><td>{x.promise}</td><td className={x.latest!==x.promise?"amberText":""}>{x.latest}</td><td><i className={`procStatus ${x.status==="风险"?"risk":x.status==="关注"?"attention":"good"}`}>{x.expedite}</i></td><td><b className={x.impact!=="无"?"redText":""}>{x.impact}</b></td><td>{x.value.toLocaleString()}</td><td><button onClick={()=>update(x.id)}>升级催交</button></td></tr>)}</tbody></table></div></section><div className="procurementBottom"><section className="card expeditingTimeline"><div className="controlsHead"><div><span>EXPEDITING MILESTONES</span><h3>VMB Cabinet · PO-26-01790</h3></div><span className="procStatus risk">项目级升级</span></div><div className="expediteFlow">{[["PO 释放","06/12","done"],["设计确认","06/28","done"],["材料齐套","07/16","active"],["FAT","07/24","next"],["发运 / 清关","08/02","next"],["现场到货","08/10","next"]].map(x=><div className={x[2]} key={x[0]}><i>{x[2]==="done"?"✓":x[2]==="active"?"•":""}</i><span><b>{x[0]}</b><small>{x[1]}</small></span></div>)}</div></section><aside className="card vendorScore"><span>VENDOR PERFORMANCE</span><h3>本季度供应商履约</h3><div className="vendorScoreNum"><b>86</b><span>/100</span></div><p><span>交期可靠度</span><b>82%</b></p><p><span>Vendor Data 准时率</span><b>94%</b></p><p><span>质量一次通过</span><b>98.1%</b></p><button className="fullPrimary" onClick={()=>notify("供应商绩效详情已打开")}>查看供应商绩效</button></aside></div></>;
}

function ReceivingView({items,update,notify}:{items:typeof receiving;update:(id:string)=>void;notify:Notify}){
  return <><div className="receivingKpis"><section className="card"><span>待检收货</span><b>12</b><small>4 项来自关键路径</small></section><section className="card"><span>IQC 通过率</span><b>96.8%</b><small>本月 186 批</small></section><section className="card"><span>隔离区物料</span><b className="redText">3</b><small>等待 NCR 处置</small></section><section className="card"><span>MTC / CoC 完整率</span><b>92%</b><small className="amberText">18 批文件待补</small></section></div><section className="card receivingBoard"><div className="controlsHead"><div><span>GOODS RECEIPT & IQC</span><h3>到货、收货与质量状态</h3><p>物料到现场不等于可安装：必须完成数量、外观、材质证书、洁净包装与 IQC 放行</p></div><div><button>打印收货标签</button><button onClick={()=>notify("收货批次已新增")}>＋ 登记到货</button></div></div><div className="receivingTable"><table><thead><tr><th>收货批次</th><th>物料</th><th>PO</th><th>到货日</th><th>存放位置</th><th>IQC 状态</th><th>质量文件</th><th>结论</th><th></th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td><code>{x.id}</code></td><td><b>{x.item}</b></td><td>{x.po}</td><td>{x.arrival}</td><td>{x.location}</td><td><i className={`receivingStatus ${x.status==="已放行"?"good":x.status==="隔离"?"risk":"attention"}`}>{x.qc}</i></td><td><span className={x.docs.includes("缺")?"redText":""}>{x.docs}</span></td><td><b className={x.status==="隔离"?"redText":x.status==="已放行"?"greenText":""}>{x.status}</b></td><td><button disabled={x.status==="已放行"} onClick={()=>update(x.id)}>{x.status==="已放行"?"已放行":"更新 IQC"}</button></td></tr>)}</tbody></table></div></section><div className="receivingBottom"><section className="card materialFlow"><div className="controlsHead"><div><span>MATERIAL FLOW</span><h3>关键材料现场流转</h3></div><button onClick={()=>notify("物料追踪详情已打开")}>物料追踪</button></div>{[["316L EP Tube","已到货","IQC 96%","CWP-GAS-L2-07"],["PFA Valve","部分到货","IQC 100%","CWP-CDS-L1-04"],["VMB Cabinet","在途 / 清关","FAT 64%","GAS-VMB-04"],["螺栓四组合","已放行","IQC 100%","CWP-FASTENER-09"]].map(x=><div className="materialFlowRow" key={x[0]}><i className={x[1].includes("已放行")?"good":x[1].includes("在途")?"attention":""}/><span><b>{x[0]}</b><small>{x[3]}</small></span><em>{x[1]}</em><strong>{x[2]}</strong></div>)}</section><aside className="card quarantine"><span>QUARANTINE & NCR</span><h3>隔离物料处置</h3><div className="quarantineRing"><b>3</b><small>批次</small></div><p><span>待补文件</span><b>2</b></p><p><span>外观 / 数量异常</span><b>1</b></p><button className="fullPrimary" onClick={()=>notify("NCR 隔离处置列表已打开")}>进入隔离处置</button></aside></div></>;
}

function CostView({contingency,setContingency,notify}:{contingency:number;setContingency:(x:number)=>void;notify:Notify}){
  const committed=24.8; const forecast=38.4*(1+contingency/100-0.08); const variance=forecast-38.4;
  return <><div className="costKpis"><section className="card"><span>批准预算 BAC</span><b>$ 38.4<small>M</small></b><p>基线版本 · 2026-06-30</p></section><section className="card"><span>已承诺成本</span><b>$ {committed}<small>M</small></b><p>64% 预算已承诺</p></section><section className="card"><span>完工预测 EAC</span><b>$ {forecast.toFixed(1)}<small>M</small></b><p className={variance>1?"redText":"greenText"}>{variance>=0?"+":""}{variance.toFixed(1)}M vs BAC</p></section><section className="card"><span>剩余管理储备</span><b>$ 2.6<small>M</small></b><p className="amberText">已使用 54%</p></section></div><div className="costLayout"><section className="card costForecast"><div className="controlsHead"><div><span>COST FORECAST · EAC</span><h3>成本承诺、实际与预测</h3><p>工程经验：不能只看已付款，要同时看 committed、accrual、forecast 和 contingency</p></div><button onClick={()=>notify("成本基线对比已打开")}>对比基线</button></div><div className="costChart"><div className="costAxis"><span>$40M</span><span>$30M</span><span>$20M</span><span>$10M</span><span>$0</span></div><div className="costPlot"><i className="gridline g1"/><i className="gridline g2"/><i className="gridline g3"/><i className="gridline g4"/><div className="bars">{[["设计",18,24,28],["土建",45,62,68],["机电",32,58,72],["工艺设备",52,74,82],["厂务材料",23,40,58],["调试",6,18,31]].map(x=><div key={x[0]}><span>{x[0]}</span><i style={{height:`${x[1]}%`}}/><i style={{height:`${x[2]}%`}}/><i style={{height:`${x[3]}%`}}/></div>)}</div><div className="costChartLegend"><span><i className="blueBar"/>已承诺</span><span><i className="cyanBar"/>实际 / 应计</span><span><i className="purpleBar"/>完工预测</span></div></div></div></section><aside className="card contingencyCard"><span>CONTINGENCY CONTROL</span><h3>项目风险储备</h3><div className="contingencyRing"><b>{contingency}%</b><small>建议值</small></div><p>当前按总预算配置 {contingency}% 风险储备，主要覆盖长周期设备、设计变更和材料价格波动。</p><label>储备调整 <b>{contingency}%</b><input type="range" min="5" max="15" value={contingency} onChange={e=>setContingency(+e.target.value)}/></label><button className="fullPrimary" onClick={()=>notify("成本预测已保存")}>保存预测</button></aside></div><section className="card costBreakdown"><div className="controlsHead"><div><span>COMMITMENT BREAKDOWN</span><h3>成本分项与承诺覆盖</h3></div><button onClick={()=>notify("成本分项明细已导出")}>导出成本报告</button></div>{[["工艺与厂务设备","$ 14.2M","$ 12.4M",87,"#165dff"],["管路、阀件与材料","$ 9.8M","$ 7.6M",78,"#00b8d9"],["土建、结构与洁净室","$ 8.6M","$ 3.2M",37,"#9b7cf4"],["安装、调试与验证","$ 5.8M","$ 1.6M",28,"#36d399"]].map(x=><div className="costBreakRow" key={x[0]}><span><b>{x[0]}</b><small>{x[1]} 预算 · 已承诺 {x[2]}</small></span><div><i style={{width:`${x[3]}%`,background:x[4]}}/></div><strong>{x[3]}%</strong><button onClick={()=>notify(`${x[0]} 成本明细已打开`)}>明细 →</button></div>)}</section></>;
}
