"use client";

import { useState } from "react";
import { facilityDomains, facilitySystems } from "@/lib/facility-systems";

type Notify = (message: string) => void;

export function ProjectCreationWizard({ open, onClose, onCreated, notify }: { open: boolean; onClose: () => void; onCreated: (project: { id: string; code: string; name: string }) => void; notify: Notify }) {
  const [draft,setDraft]=useState({code:"",name:"",region:"CN",fab:"",phase:"concept",templateCode:"FAB_FULL",numberPrefix:"",defaultWastePct:5});
  const [systemCodes,setSystemCodes]=useState(facilitySystems.map((item)=>item.code));
  const [saving,setSaving]=useState(false); const [error,setError]=useState("");
  if(!open)return null;
  const update=(key:string,value:string|number)=>setDraft((current)=>({...current,[key]:value}));
  const toggle=(code:string)=>setSystemCodes((current)=>current.includes(code)?current.filter((item)=>item!==code):[...current,code]);
  const save=async()=>{setSaving(true);setError("");try{const response=await fetch("/api/project-bootstrap",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...draft,numberPrefix:draft.numberPrefix||draft.code,systemCodes})});const payload=await response.json();if(!response.ok)throw new Error(payload.error||"项目创建失败");notify(`项目 ${payload.project.code} 已创建并初始化 ${payload.systems.length} 个系统`);onCreated(payload.project)}catch(cause){setError(cause instanceof Error?cause.message:"项目创建失败")}finally{setSaving(false)}};
  return <><div className="overlay projectWizardOverlay" onClick={()=>!saving&&onClose()}/><aside className="projectWizard"><header><div><span>PROJECT BOOTSTRAP</span><h2>创建 FAB 项目</h2><p>一次建立项目、编号规则、标准系统、权限边界和文件分类。</p></div><button disabled={saving} onClick={onClose}>×</button></header>{error&&<div className="masterError"><i>!</i><span><b>项目不能创建</b><small>{error}</small></span></div>}<div className="projectWizardBody"><section><h3>01 · 项目身份</h3><div className="projectWizardFields"><label><span>项目编号 *</span><input value={draft.code} onChange={(event)=>update("code",event.target.value)} placeholder="FAB-2026-001"/></label><label className="wide"><span>项目名称 *</span><input value={draft.name} onChange={(event)=>update("name",event.target.value)}/></label><label><span>国家 / 地区</span><input value={draft.region} onChange={(event)=>update("region",event.target.value)}/></label><label><span>厂区 / Fab</span><input value={draft.fab} onChange={(event)=>update("fab",event.target.value)}/></label><label><span>项目阶段</span><select value={draft.phase} onChange={(event)=>update("phase",event.target.value)}><option value="concept">概念设计</option><option value="basic_design">基础设计</option><option value="detailed_design">详细设计</option><option value="construction">施工</option></select></label><label><span>编号前缀</span><input value={draft.numberPrefix} onChange={(event)=>update("numberPrefix",event.target.value)} placeholder={draft.code||"自动使用项目编号"}/></label><label><span>默认采购余量 %</span><input type="number" min="0" max="30" value={draft.defaultWastePct} onChange={(event)=>update("defaultWastePct",Number(event.target.value))}/></label></div></section><section><h3>02 · 标准系统模板</h3><p>默认初始化完整 FAB 13 系统，可按项目范围取消。</p>{facilityDomains.map((domain)=><div className="projectWizardDomain" key={domain.id}><b>{domain.name}</b><div>{facilitySystems.filter((item)=>item.domainId===domain.id).map((system)=><button className={systemCodes.includes(system.code)?"active":""} key={system.code} onClick={()=>toggle(system.code)}><i>{systemCodes.includes(system.code)?"✓":"+"}</i><span>{system.code} · {system.shortName}</span></button>)}</div></div>)}</section><section><h3>03 · 自动建立</h3><div className="projectBootstrapSummary">{["D1 项目主档","项目级 RBAC 边界","系统主数据","技术规格书目录","图纸与计算书目录","设备厂与 ITP/FAT 目录","竣工移交目录"].map((item)=><span key={item}>✓ {item}</span>)}</div></section></div><footer><span>将创建 {systemCodes.length} 个系统</span><button disabled={saving} onClick={onClose}>取消</button><button className="primaryButton" disabled={saving||!draft.code.trim()||!draft.name.trim()||!systemCodes.length} onClick={()=>void save()}>{saving?"初始化中…":"创建并进入项目"}</button></footer></aside></>;
}