"use client";

import { useMemo, useState } from "react";

type Notify=(message:string)=>void;

const systems=[
  {id:"UTL",name:"动力公用工程",en:"Utilities",icon:"⚡",color:"blue",scope:"CDA · N₂ · PCW · Chilled Water · Electrical · Emergency Power",progress:76,design:92,mc:58,rfc:26,risk:"2 个接口关注",tag:"UTL-01~28",owner:"Utilities Lead",metric:"18.6 MW"},
  {id:"CR",name:"洁净室与洁净包",en:"Cleanroom Package",icon:"▦",color:"cyan",scope:"ISO 4 / ISO 5 · MAU · FFU · HEPA · 压差 · 洁净验证",progress:68,design:84,mc:44,rfc:12,risk:"封闭条件 9 项",tag:"CR-01~16",owner:"Cleanroom Lead",metric:"42,800 m²"},
  {id:"WTR",name:"纯水与废水",en:"UPW / Wastewater",icon:"≈",color:"green",scope:"RO · EDI · UV · TOC · UPW Loop · 酸碱废水 · 中和",progress:63,design:88,mc:38,rfc:18,risk:"1 个排放许可",tag:"WTR-01~22",owner:"Water Lead",metric:"1,240 m³/d"},
  {id:"EXH",name:"工艺排风",en:"Process Exhaust",icon:"⌁",color:"purple",scope:"酸排 · 碱排 · 溶剂排 · 一般排风 · Scrubber · 排放监测",progress:57,design:79,mc:31,rfc:9,risk:"AE-03 设备延期",tag:"EXH-01~19",owner:"Exhaust Lead",metric:"860,000 CMH"},
  {id:"FIRE",name:"消防与生命安全",en:"Fire & Life Safety",icon:"♢",color:"orange",scope:"消防水 · 喷淋 · VESDA · F&G · 气体探测 · 防火分区",progress:71,design:91,mc:47,rfc:22,risk:"AHJ 书面意见",tag:"FLS-01~14",owner:"EHS / Fire Lead",metric:"14 zones"},
  {id:"CTRL",name:"机电自控与能源管理",en:"MEP / Controls",icon:"⌘",color:"gray",scope:"BMS · EPMS · SCADA · PLC · I/O · 联锁 · 能源计量",progress:49,design:73,mc:18,rfc:4,risk:"I/O 点表缺口",tag:"CTL-01~34",owner:"Controls Lead",metric:"12,486 I/O"},
];

const interfaces=[
  ["IF-UTL-014","CDA 站房压力与 Tool Utility Matrix","动力","工艺 / 自控","确认压力 0.72 MPa 与低压报警值","待确认","高"],
  ["IF-CR-022","洁净室压差与消防排烟联动","洁净","消防 / HVAC / BMS","确认火灾模式下压差策略与风阀位置","协调中","高"],
  ["IF-WTR-031","酸碱废水中和池与排放许可","废水","EHS / 土建","完成排放限值和取样点复核","待确认","高"],
  ["IF-EXH-018","Scrubber 联锁与 VMB Gas Detection","排风","特气 / 自控","形成 Cause & Effect Rev.C","已关闭","中"],
  ["IF-CTL-041","BMS / EPMS 网络与时间同步","自控","IT / 电气","确定 VLAN、NTP、冗余链路方案","进行中","中"],
];

const checks=[
  ["边界与 Tag 清单冻结","系统边界图、设备 Tag、管线号和 I/O 点表具备版本","完成"],["设计基准与计算书","容量、峰值、冗余、压力、流量和能耗计算已批准","完成"],["Vendor Data 与接口","关键设备资料、联锁、维护空间和电气条件已锁定","进行中"],["施工图与工作包","IFC 图、材料、施工方案和 ITP 已关联","进行中"],["试验与调试包","压力 / 气密 / 冲洗 / 功能 / 联锁试验包已建立","待开始"],["移交与运营资料","SOP、培训、备件、竣工图和 O&M 已纳入","待开始"],
];

export function SystemEngineeringPage({notify}:{notify:Notify}){
  const [selected,setSelected]=useState("UTL"); const [tab,setTab]=useState("系统总览"); const [interfaceRows,setInterfaceRows]=useState(interfaces); const [checksState,setChecksState]=useState(checks);
  const current=systems.find(x=>x.id===selected)??systems[0];
  const closeInterface=(id:string)=>{setInterfaceRows(interfaceRows.map(x=>x[0]===id?[...x.slice(0,5),"已关闭",x[6]]:x));notify(`${id} 接口问题已关闭`)};
  const toggleCheck=(index:number)=>{setChecksState(checksState.map((x,i)=>i===index?[x[0],x[1],x[2]==="完成"?"进行中":"完成"]:x));notify(`${checksState[index][0]} 状态已更新`)};
  return <>
    <div className="moduleTop systemTop"><div><span>SYSTEM ENGINEERING DOMAINS</span><h2>厂务系统工程域总览</h2><p>将动力、洁净、水、排风、消防和自控按系统边界、接口、测试包与移交状态统一管理</p></div><div className="moduleActions"><button className="softButton" onClick={()=>notify("系统边界清单已导出")}>导出系统清单</button><button className="primaryButton" onClick={()=>notify("新系统边界已创建")}>＋ 新建系统边界</button></div></div>
    <div className="systemDomainKpis"><section className="card"><span>系统域</span><b>6<small>个</small></b><p>34 个子系统 · 128 个系统包</p></section><section className="card"><span>设计成熟度</span><b>82<small>%</small></b><p>2 个域低于 G3 目标</p></section><section className="card"><span>接口事项</span><b>26<small>项</small></b><p className="amberText">9 项影响关键路径</p></section><section className="card"><span>测试包</span><b>173<small>包</small></b><p>通过率 94.2%</p></section><section className="card"><span>移交准备</span><b>38<small>%</small></b><p className="redText">A 类 Punch 6 项</p></section></div>
    <div className="systemTabs">{["系统总览","接口与联锁","系统准入","测试与移交"].map(x=><button key={x} className={tab===x?"active":""} onClick={()=>setTab(x)}><i>{x==="系统总览"?"◎":x==="接口与联锁"?"◇":x==="系统准入"?"✓":"⌁"}</i><span>{x}</span><small>{x==="系统总览"?"6 domains":x==="接口与联锁"?"Interface Register":x==="系统准入"?"Readiness Gates":"Test & Handover"}</small></button>)}</div>
    {tab==="系统总览"&&<OverviewView systems={systems} selected={selected} setSelected={setSelected} current={current} notify={notify}/>} 
    {tab==="接口与联锁"&&<InterfaceView rows={interfaceRows} close={closeInterface} notify={notify}/>} 
    {tab==="系统准入"&&<ReadinessView checks={checksState} toggle={toggleCheck} current={current} notify={notify}/>} 
    {tab==="测试与移交"&&<SystemTestingView current={current} notify={notify}/>} 
  </>;
}

function OverviewView({systems,selected,setSelected,current,notify}:{systems:typeof systems;selected:string;setSelected:(x:string)=>void;current:typeof systems[number];notify:Notify}){
  return <><div className="domainGrid">{systems.map(s=><button className={`card domainCard ${selected===s.id?"active":""}`} key={s.id} onClick={()=>setSelected(s.id)}><div className={`domainIcon ${s.color}`}>{s.icon}</div><div className="domainHeader"><span>{s.id} · {s.tag}</span><i className={s.color}>{s.progress>=70?"正常":s.progress>=55?"关注":"风险"}</i></div><h3>{s.name}</h3><small className="domainEn">{s.en}</small><p>{s.scope}</p><div className="domainProgress"><span><b>总体进度</b><em>{s.progress}%</em></span><div><i style={{width:`${s.progress}%`}}/></div></div><div className="domainStats"><span>设计 <b>{s.design}%</b></span><span>MC <b>{s.mc}%</b></span><span>RFC <b>{s.rfc}%</b></span></div><footer><span><i className={`domainDot ${s.color}`}/>{s.risk}</span><em>{s.metric}</em></footer></button>)}</div><div className="domainDetailLayout"><section className="card domainDetail"><div className="systemHead"><div className={`domainIcon ${current.color}`}>{current.icon}</div><div><span>{current.id} · SYSTEM BOUNDARY</span><h3>{current.name}</h3><p>{current.scope}</p></div><button onClick={()=>notify(`已打开 ${current.name} 系统边界图`)}>打开边界图 →</button></div><div className="boundaryFlow"><div><i>01</i><span><b>设计边界</b><small>Design / Calculation / Spec</small></span></div><em>→</em><div><i>02</i><span><b>采购边界</b><small>Equipment / Material / Vendor</small></span></div><em>→</em><div><i>03</i><span><b>施工边界</b><small>CWP / ITP / QA-QC</small></span></div><em>→</em><div><i>04</i><span><b>调试边界</b><small>Test Pack / Interlock / Handover</small></span></div></div><div className="domainMetrics"><div><span>设计成熟度</span><b>{current.design}%</b><div><i style={{width:`${current.design}%`}}/></div></div><div><span>机械完工 MC</span><b>{current.mc}%</b><div><i className="green" style={{width:`${current.mc}%`}}/></div></div><div><span>RFC 准备度</span><b>{current.rfc}%</b><div><i className="purple" style={{width:`${current.rfc}%`}}/></div></div><div><span>关键风险</span><b className="redText">{current.risk}</b><small>需系统负责人签字确认</small></div></div></section><aside className="card domainNotes"><span>SYSTEM OWNER NOTES</span><h3>{current.owner}</h3><p>本域的设计输入、接口和测试边界由系统负责人统一签字，跨专业事项不能只在单专业图纸中关闭。</p><div><b>当前关注</b><span>{current.risk}</span></div><button className="fullPrimary" onClick={()=>notify(`${current.name} 责任人会议已创建`)}>召集系统评审</button></aside></div></>;
}

function InterfaceView({rows,close,notify}:{rows:typeof interfaces;close:(id:string)=>void;notify:Notify}){
  return <><section className="card interfaceHero"><div><span>INTERFACE & CAUSE / EFFECT</span><h2>系统接口与联锁矩阵</h2><p>实际工程中，最容易造成返工的不是单专业错误，而是系统边界和联锁责任未明确。</p></div><div className="interfaceCounts"><b>26<small>开放接口</small></b><b className="redText">9<small>关键影响</small></b><b>14<small>跨专业</small></b></div></section><section className="card domainInterfaceBoard"><div className="systemHead"><div><span>INTERFACE REGISTER</span><h3>接口责任、验收条件与关闭状态</h3></div><button onClick={()=>notify("新接口事项已创建")}>＋ 新增接口</button></div><div className="domainInterfaceTable"><table><thead><tr><th>接口编号</th><th>系统边界 / 责任专业</th><th>必须确认的工程条件</th><th>状态</th><th>风险</th><th></th></tr></thead><tbody>{rows.map(x=><tr key={x[0]}><td><code>{x[0]}</code></td><td><b>{x[1]}</b><small>{x[2]} → {x[3]}</small></td><td>{x[4]}</td><td><i className={`interfaceState ${x[5]==="已关闭"?"closed":x[5]==="协调中"?"working":"pending"}`}>{x[5]}</i></td><td><b className={x[6]==="高"?"redText":"amberText"}>{x[6]}</b></td><td><button disabled={x[5]==="已关闭"} onClick={()=>close(x[0])}>{x[5]==="已关闭"?"已关闭":"关闭接口"}</button></td></tr>)}</tbody></table></div></section><div className="causeEffect"><section className="card causeCard"><div className="systemHead"><div><span>CAUSE & EFFECT</span><h3>典型联锁链路</h3></div><button onClick={()=>notify("Cause & Effect 矩阵已导出")}>导出矩阵</button></div>{[["Cl₂ 泄漏报警","Gas Detector GD-014","关闭 VMB 气动阀","启动局部排风","通知 F&G / BMS"],["洁净室火灾模式","Fire Alarm Zone 04","关闭 MAU / FFU","启动排烟 / 防火阀","释放门禁 / 广播"],["UPW 低流量","Flow Switch FS-22","报警并锁定设备","切换备用泵","记录 BMS 事件"],["Scrubber 高液位","LT-301 High High","停止工艺排风","关闭旁路风阀","通知 EHS / 运营"]].map(x=><div key={x[0]}><b>{x[0]}</b>{x.slice(1).map((y,i)=><span key={y}><i>{i+1}</i>{y}</span>)}</div>)}</section><aside className="card alarmCard"><span>ALARM / EVENT QUALITY</span><h3>报警点表质量</h3><div className="alarmScore"><b>91%</b><span>12,486 I/O 中<br/>11,362 已完成 Cause & Effect</span></div><p><span>高优先级报警</span><b>184</b></p><p><span>未定义响应</span><b className="redText">26</b></p><p><span>未完成 SAT</span><b className="amberText">41</b></p><button className="fullPrimary" onClick={()=>notify("报警点表差异清单已打开")}>查看差异清单</button></aside></div></>;
}

function ReadinessView({checks,toggle,current,notify}:{checks:typeof checks;toggle:(i:number)=>void;current:typeof systems[number];notify:Notify}){
  const done=checks.filter(x=>x[2]==="完成").length; return <><section className="card readinessHero"><div><span>SYSTEM READINESS GATE</span><h2>{current.name} · G3 / RFC 准入</h2><p>准入不是“看起来差不多”，而是每项证据、责任人和版本都能追溯。</p></div><div className="readinessScore"><b>{Math.round(done/checks.length*100)}%</b><span>{done} / {checks.length} 项完成</span></div></section><div className="readinessLayout"><section className="card gateEvidence"><div className="systemHead"><div><span>GATE EVIDENCE CHECKLIST</span><h3>系统准入证据清单</h3></div><button onClick={()=>notify("准入证据包已生成")}>生成证据包</button></div>{checks.map((x,i)=><button className="evidenceRow" key={x[0]} onClick={()=>toggle(i)}><i className={x[2]==="完成"?"done":x[2]==="进行中"?"working":""}>{x[2]==="完成"?"✓":x[2]==="进行中"?"•":""}</i><span><b>{x[0]}</b><small>{x[1]}</small></span><em className={x[2]==="完成"?"done":x[2]==="进行中"?"working":""}>{x[2]}</em><strong>查看证据 →</strong></button>)}</section><aside className="card permitCard"><span>PERMIT / AHJ</span><h3>许可与外部验收</h3><p><i className="done">✓</i><span><b>消防策略原则认可</b><small>AHJ Letter · Rev.B</small></span></p><p><i className="working">•</i><span><b>危化品存储许可</b><small>待补充库存计算</small></span></p><p><i>!</i><span><b>排放许可</b><small>需补充废水取样点</small></span></p><button className="fullPrimary" onClick={()=>notify("许可矩阵已打开")}>打开许可矩阵</button></aside></div></>;
}

function SystemTestingView({current,notify}:{current:typeof systems[number];notify:Notify}){
  return <><div className="testKpis"><section className="card"><span>本域试验包</span><b>28</b><small>已完成 17 · 执行中 6</small></section><section className="card"><span>压力 / 气密</span><b>94%</b><small>2 包待业主见证</small></section><section className="card"><span>联锁 SAT</span><b>76%</b><small className="amberText">41 个报警点待测试</small></section><section className="card"><span>系统移交</span><b>38%</b><small className="redText">A 类 Punch 2 项</small></section></div><section className="card systemTestBoard"><div className="systemHead"><div><span>TEST & HANDOVER PACK</span><h3>{current.name} · 测试与移交包</h3></div><button onClick={()=>notify("新测试包已创建")}>＋ 新建测试包</button></div>{[["TP-UTL-014","CDA / N₂ 站房压力与露点","气密 / 露点","已完成",100],["TP-UTL-022","PCW 二次泵组联动","流量 / 振动 / 联锁","执行中",72],["TP-UTL-028","应急电源切换测试","ATS / EPMS / Load Bank","待开始",18],["TP-UTL-031","Utility Header 运营移交","SOP / 培训 / 备件 / Punch","待开始",8]].map(x=><div className="systemTestRow" key={x[0]}><i className={x[3]==="已完成"?"done":x[3]==="执行中"?"working":""}>{x[3]==="已完成"?"✓":x[3]==="执行中"?"•":""}</i><span><code>{x[0]}</code><b>{x[1]}</b><small>{x[2]}</small></span><div><span><b>{x[4]}%</b>{x[3]}</span><p><i style={{width:`${x[4]}%`}}/></p></div><button onClick={()=>notify(`${x[0]} 详情已打开`)}>查看包 →</button></div>)}</section><div className="handoverGrid"><section className="card handoverDocs"><div className="systemHead"><div><span>HANDOVER DOSSIER</span><h3>运营移交文件包</h3></div><button onClick={()=>notify("移交文件包已生成")}>生成目录</button></div>{[["竣工图与模型","As-built / IFC / Tag Data",92],["O&M 与 SOP","操作、维护、应急响应",61],["培训与能力证明","运营、EHS、维修团队",44],["备件与耗材","关键备件、保修、供应商",77]].map(x=><div className="handoverDocRow" key={x[0]}><span><b>{x[0]}</b><small>{x[1]}</small></span><div><i style={{width:`${x[2]}%`}}/></div><em>{x[2]}%</em></div>)}</section><aside className="card handoverBlock"><span>TURNOVER BLOCKERS</span><h3>移交阻断项</h3><div className="blockerNum"><b>2</b><small>A 类 Punch</small></div><p><span>测试记录未签字</span><b>4</b></p><p><span>SOP 未批准</span><b>3</b></p><p><span>培训未完成</span><b>2</b></p><button className="fullPrimary" onClick={()=>notify("移交阻断项清单已打开")}>查看阻断项</button></aside></div></>;
}
